### ISSUE TITLE
Feedback and a request

### ISSUE THREAD

**Issue by elderapo** [remorses/genql#1]
Wow, this library is awesome! I've been looking for a good typesafe GraphQL client for a long time :D

Some feedback:

Is it necessary to have 2 different clients for subscriptions and queries/mutations? I think it would be better/easier to have just one. This way authentication and other stuff don't have to be set up twice. Also, it would be nice if it was possible to configure query/mutations to be executed through WebSocket (it doesn't always make sense but if your app already uses subscriptions why not!).

I will play around with it some more and will let you know if I find something. Once again, good job!

**Comment by remorses** [comment]
I made 2 different clients so that if you don’t use the subscription client it can be tree shaken away to reduce bundle size

Also the clients use 2 different connections so it wakes sense to use 2 different clients

I don’t plan to add web sockets support on queries, what would be the benefit?

Thank you for your feedback ❤️

**Comment by elderapo** [comment]
> I made 2 different clients so that if you don’t use the subscription client it can be tree shaken away to reduce bundle size

That's a valid argument. However, it can be worked around by making it optional like in `apollo`/other popular clients where you have to feed `subscription` client to `normal` one to make it work with subscriptions.

> Also the clients use 2 different connections so it wakes sense to use 2 different clients

Not sure I understand. You can send `query`/`mutation`/`subscriptions` over WebSocket so you don't always need 2 different "connections".

> I don’t plan to add web sockets support on queries, what would be the benefit?

If you already have a WebSocket connection opened/estabilished (in case you have at least 1 subscription open) it makes sense to reuse that websocket for sending queries/mutations as well. Also if you're working with authenticated subscriptions it makes sense to have `mutation(authenticate)` that you feed "auth token" and it authenticates you (associates your WebSocket with a specific user) so later you can use `subscription(thisUserSomeEvent)`. Most popular graphql clients allow that so it would be a bummer if this library wouldn't :(

**Comment by remorses** [comment]
Now i remember that i separated the 2 clients to lower the number of generic type arguments

Typescript give issues when you have 9 type arguments so I created a separate function

If you want to have more advanced client features you can use `genql` with apollo or other clients following [this guide](https://genql.now.sh/docs/usage/usage-with-other-clients)

**Comment by jasonkuhrt** [comment]
Also interested in a single client for all graphql operation types.

> Now i remember that i separated the 2 clients to lower the number of generic type arguments

How open are you to adjusting the generation so that there are fewer generics in use in the first place?

Since it is generated, in theory, it should be possible to avoid generics almost completely?

Such an approach usually makes the developer experience of autocomplete significantly better too.

**Comment by remorses** [comment]
Yes generics aren't really necessary there, i will work on this in the next days

**Comment by remorses** [comment]
I removed the generics, now cmd+click on a field takes you to the request type

I also added the subscription in the main client

Let me know if you find any issues with the new version

**Comment by elderapo** [comment]
1. I haven't previously checked subscription support in browser (for example in CRA). But now I am getting `Error: ws does not work in the browser. Browser clients must use the native WebSocket object` when trying to use subscriptions in the new client. It would be nice if subscription options accepted `ws` implementation as options or automatically picked implementation based on the environment.
2. Is `query`/`mutation` transportation layer (http vs ws) now configurable or do you plan to support it in the future?

**Comment by remorses** [comment]
I don't plan on adding the ws transport on queries and mutations, it would add too much complexity

Probably the best way  to pass subscription options is to pass directly the transport as an option? Something like this

```ts
import { SubscriptionClient } from "subscriptions-transport-ws";

const client = createClient({
  subscription: new SubscriptionClient("ws://localhost:3000/graphql", {
    reconnect: true
  })
})
```

This way you have total control on the transport options without any indirection and the transport could be tree shaken (about 15Kb).

What do you think?  @jasonkuhrt do you like this approach too?

**Comment by elderapo** [comment]
> I don't plan on adding the ws transport on queries and mutations, it would add too much complexity

Is this still the case? I would really like to use `genql` instead of `urql`/`apollo` because it has so much better DX. The lack of this feature is stopping me and potentially other people from using it.

**Comment by jasonkuhrt** [comment]
@remorses that seems like a good start. Maybe once a great solution emerges it can be candidated for bundling but I see your proposal as a fine starting point.

**Comment by thelinuxlich** [comment]
Is this working? I tried adding a `graphql-ws` client to the subscription option but it doesn't have the correct type
