### ISSUE TITLE
GraphQL aliases

### ISSUE THREAD

**Issue by dhmacs** [remorses/genql#10]
How do you specify [aliases](https://graphql.org/learn/queries/#aliases) ?

e.g.:

```graphql
{
  empireHero: hero(episode: EMPIRE) {
    name
  }
  jediHero: hero(episode: JEDI) {
    name
  }
}
```

**Comment by remorses** [comment]
Currently you can't do aliases, you can do separate the requests in different objects and use batching to limit the network requests (wrapping inside a `Promise.all`)

there is an example [here](https://genql.now.sh/docs/usage/batching-queries)

**Comment by remorses** [comment]
I won't implement this, i will add native batching support instead

**Comment by dhmacs** [comment]
@remorses I think I have a scenario where batching is not a valid replacement for aliases.

Suppose I'm fetching a list of items with nested details like this:

```graphql
query getOrders {
  orders {
    id
    name
    allTasks: tasks_aggregate { 
      aggregate { count } 
    }
    completedTasks: tasks_aggregate(
      where: { task: { completed_at: { _is_null: false } } }
    ) { 
      aggregate { count } 
    }
  }
}
```

To replicate this with batching I would have to fetch the list of items twice and this doubles the cost of the query! 😬

**Comment by remorses** [comment]
Maybe I could add support for this passing an array of objects queries and merge them using something like https://github.com/domasx2/graphql-combine-query

This way you would get the same power of aliases without batching, but I would need to add more complex logic to rename the implicit aliases back to their original name (only when you query fields with same name)

**Comment by biancazzurri** [comment]
How batching resolves this issue exactly?
For example, there are N types:
type A1 {
   value: <subtypeA1>
}
.
.
.
type AN {
   value: <subtypeAN>
}

union A = A1 | A2 ... AN

type X {
     value: A
}

so, N clients needed?

**Comment by dhmacs** [comment]
@remorses for some reason I got the notification only now. 
Anyway, looks like it could be a solution, although I'm not sure this way the API would be as intuitive as with using GraphQL literals.

In terms of API maybe something like this might better resemble the alias DX. Basically it adds a third array item to specify aliases.
```ts
orders: [ 
  {}, 
  {
    id: true,
    name: true,
    allTasks: { 
      aggregate { count } 
    },
    completedTasks: [{
      where: { task: { completed_at: { _is_null: false } } }
    }, { 
      aggregate { count } 
    }]
  }, 
  {
    allTasks: "tasks_aggregate",
    completedTasks: "tasks_aggregate"
  }
]
```
