### ISSUE TITLE
Add support for directives

### ISSUE THREAD

**Issue by remorses** [remorses/genql#104]
The syntax would be

```ts
client.query({ field: { __directive: '@something' } })
```

Upvote this issue with a 👍 if you care about directives

**Comment by Relaxe111** [comment]
I think it will be a really nice feature. In hasure we have directive like:
```
query{
  anonymous_queries{
    properties @include(if: true)
  }
}
```
With this syntax will be possible to achieve the same?

**Comment by theomessin** [comment]
Any update on this?

**Comment by berenddeboer** [comment]
It's pretty common to have directives like @aws_iam and @aws_api_key.

**Comment by shiftlabs1** [comment]
@remorses any update on this feature ?
