### ISSUE TITLE
Bug: Type collision

### ISSUE THREAD

**Issue by dhmacs** [remorses/genql#11]
Hasura let's you specify big integers that are exposed on the GraphQL endpoint with type `bigint`.

Given that `bigint` is a reserved word in typescript (see [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-2.html#bigint)), the following generated code breaks:

```typescript
export type bigint=any
```

It gives a `Type alias name cannot be 'bigint'` error.

## Possible solution

To work around this scalars can be defined like GraphQL codegen does:
```
export type Scalars = {
  ID: string,
  String: string,
  Boolean: boolean,
  Int: number,
  Float: number,
  uuid: string,
  bigint: any,
};
```

So that they are used like this: `Scalars["bigint"]`. 

As a cool addition, you can make scalar types configurable e.g.
```typescript
{
  uuid: "string",
}
```
So they are typed correctly and you don't loose type inference due to the use of `any`

**Comment by remorses** [comment]
Now you can pass custom types with the `-S or --scalar` flag
