### ISSUE TITLE
Type errors on the generated client

### ISSUE THREAD

**Issue by solaldunckel** [remorses/genql#113]
![Screenshot 2023-03-16 at 10 43 37](https://user-images.githubusercontent.com/37122137/225578565-0b4c8358-f2f7-4d2e-937f-dbd54ffbe316.png)

I'm getting some errors when type-checking the generated client when `strict` is set to true in my `tsconfig.json`.

**Comment by Julien-R44** [comment]
Same here. I made a script on my side to add an eslint-disable and ts-nocheck in the generated files after the generation

Would you accept a PR for that? @remorses I can do it if you are ok👍

**Comment by remorses** [comment]
That’s a good idea, I will add those directives

**Comment by remorses** [comment]
https://changelog.genql.dev/
