### ISSUE TITLE
How to use AbortController with the client? 

### ISSUE THREAD

**Issue by Hartha-aloufi** [remorses/genql#114]
Firstly, thank you for this great lib.

I want to cancel a mutation, I used `Abortcontroller` wtih `axios` and `fetch` before but I can't find how to use it with Genql?

I see that you can pass `signal` to the `createClient` function but I'm wondering how a top level controller could be used?

**Comment by remorses** [comment]
You could create a new client every time you want to use an `Abortcontroller`, `createClient` is a cheap operation

Or you could use your own `fetch` function and generate the query and variables with `generateQueryOp`: https://genql.dev/docs/usage/integrate-with-other-graphql-clients
