### ISSUE TITLE
Possible to change type assignment approach

### ISSUE THREAD

**Issue by nowlena** [remorses/genql#117]
Would it be possible to not output type assignment like shown below as "this breaks":

```ts
// this breaks
const typeName = <LinkedType | string>field.type;

// this works
const typeName = field.type as LinkedType | string;
```

I believe that the "breaking" syntax above is narrowing the type as if you were to use the `as` keyword but I'm not 100% on that.

The problem I have is that my generated types can't be used because NextJS throws:

```sh
Unexpected token `LinkedType`. Expected jsx identifier
```

Thank you in advance

**Comment by remorses** [comment]
https://changelog.genql.dev/
