### ISSUE TITLE
Question - How to use generated types

### ISSUE THREAD

**Issue by bennyk8y** [remorses/genql#120]
Hi, i want to use the generated type in every component in the code.
But the generated type has a `__typename` non nullable property, but i'm not necessarily requesting it in the api.
It means that i cannot pass the result of a query to a function that receives the generated type unless i requested `__typename`.
Did i misunderstood something?

**Comment by remorses** [comment]
You can either use `Partial<Type>` or wrap your genql query in a function and use `ReturnType<typeof functionName>`

**Comment by remorses** [comment]
`__typename` is required because it has type `String!`

**Comment by Hartha-aloufi** [comment]
Omitting "__typename" seems reasonable `Omit<Type, "__typename">

**Comment by jack-allocate** [comment]
Omit is the best option here, but is still not great. Now everywhere that I use one of the generated result types, I have to wrap it in `Omit<Type, "__typename">`.

It would be nice if the CLI had an option to generate response types excluding `__typename`.
