### ISSUE TITLE
Q: Fragment support

### ISSUE THREAD

**Issue by donferi** [remorses/genql#123]
Hey, I might be missing something here, but I'm looking for a way to produce fragments similar to generateQueryOp.

I'm trying to work with Graphql such that each of my react server components can define a fragment, and then the root component can bundle them all up into a single query. It would be perfect if it could support fragment masking, like in [this blogpost](https://the-guild.dev/blog/unleash-the-power-of-fragments-with-graphql-codegen).

Can I pull this off with genql? Any ideas?

**Comment by remorses** [comment]
A fragment is simply part of a query, given that in Genql a query is simply an object you can split it in smaller parts that you can compose later

**Comment by remorses** [comment]
Example here https://genql.dev/converter

you can use that tool to convert existing queries

**Comment by donferi** [comment]
Thanks for the quick reply! I'm aware that I can `...fragment` but I lose all TS typings when constructing it right? Ideally I would be able to build a type-safe fragment that will be user later on by a query if that makes sense.

**Comment by remorses** [comment]
That’s a trade-off 

imo you should just query the data at the root and pass it to the components as props or context

**Comment by donferi** [comment]
It would be nice for each component to define their data needs, similar to relay, and compose the query on the root component.

Scales much better, queries are always up-to-date with what the components need, when you delete something you don't have to remember to go and delete it from the root query, etc.

But it's your project 🤷‍♀️.
