### ISSUE TITLE
Null removed from union

### ISSUE THREAD

**Issue by donferi** [remorses/genql#124]
I've been loving genql! Thank you so much for this!

I'm having an issue, I'm not sure if this is my misunderstanding and a user error tho, I'll try to describe it.

I have the following schema:

```gql
type Book {
  title: String!
  publisher: String  # Note null field
  author: Author     # Note null field
}

type Author {
  name: String!
}

type Query {
  book: Book!
}
```

The generator creates this correct type (among other things):
```ts
export interface Book {
    title: Scalars['String']
    publisher: (Scalars['String'] | null)
    author: (Author | null)
    __typename: 'Book'
}
```

However, using the following query I'm noticing something odd:

```ts
const { book } = await client.query({
  book: {
    title: true,
    publisher: true,
    author: {
      name: true,
    }
  }
});

const title = book.title; // string - correct
const publisher = book.publisher; // string | null - correct
const author = book.author; // Author - Maybe incorrect, shouldn't this be Author | null?
```

For some reason when I'm not using a `Scalar` the union with `null` gets lost. This makes the code a bit unsafe as I can do something like `book.author.name.length` and TS won't complain.

I may be wrong but my guess is that this has gone unnoticed since before v5 this would return also `undefined`. While "incorrect" it made the code a bit safer.

**Comment by remorses** [comment]
Fixed in v6, had to do a major version because it can be a breaking change
