### ISSUE TITLE
Feature request: Add operation name to every call

### ISSUE THREAD

**Issue by bennyk8y** [remorses/genql#125]
It would be nice to have name operations without the need to manually set the `__name` field.
In requests that contain single query/mutation its straight forward.
In requests with multiple queries/mutations it can sort the operation names alphabetically and join with "_" separator.

Example of a named operation which is currently can be achieved only by providing `__name`:
```
query Me {
  user {
     name
     id
   }
}
```

example of a non named operation which is the default behavior in genql:
```
query {
  user {
     name
     id
   }
}
```

**Comment by bennyk8y** [comment]
Tools like [msw](https://mswjs.io) relies on the operation name to know what to mock.
Logrocket automatically adds the operationName to any log.
Having it will just simplify the integration with other tools.

**Comment by remorses** [comment]
What name would you give in your example query?

**Comment by bennyk8y** [comment]
I would give it the name `user`.
I would expect that having this code in genql:
```js
client.query({
   user: {
     name: true,
     id: true
   },
});
```

would result this query:
```
query user {
  user {
     name
     id
   }
}
```

This code:
```
client.query({
  __name: "Me",
   user: {
     name: true,
     id: true
   },
});
```
would result this query (i believe its the current behavior):
```
query Me {
  user {
     name
     id
   }
}
```

**Comment by bennyk8y** [comment]
@remorses any thoughts? our development teams will really appreciate such feature

**Comment by bennyk8y** [comment]
Any update?

**Comment by subzero79** [comment]
I thinks is already implemented

https://github.com/remorses/genql/blame/master/cli/src/runtime/generateGraphqlOperation.ts#L163

I just checked in my client and the operationName is sent on the query document

**Comment by remorses** [comment]
I am closing this, genql won’t generate an automatic operation name

**Comment by subzero79** [comment]
Sorry my mistake I thought it was the operationName but the request was to do automatic name when no name was given.
