### ISSUE TITLE
Feature request: response extensions

### ISSUE THREAD

**Issue by fdiogo** [remorses/genql#126]
The latest spec states that the response might have three fields: `data`, `errors` and `extensions`. Extensions here work in the same way as in `errors[number].extensions`, it's open for implementers to add whatever they might want.

https://spec.graphql.org/October2021/#sel-DAPHDJAACLAnxP
> The response map may also contain an entry with key extensions. This entry, if set, must have a map as its value. This entry is reserved for implementors to extend the protocol however they see fit, and hence there are no additional restrictions on its contents.

Examples of potentially useful extensions at this level would be: `correlation_id`, `status`, etc..

We're loving our experience with `genql`, it's a game changer. We'd love to have this if the team thinks it's a good idea, we might able to open a PR with a working example

**Comment by remorses** [comment]
I will do more research on this

**Comment by MrFoxPro** [comment]
I want to request similiar feature: allow to completely override fetcher, or at least add option not to thorw errors. I want to handle them as return value, not exceptions

**Comment by MrFoxPro** [comment]
@remorses I want to request similiar feature: allow to completely override fetcher, or at least add option not to thorw errors. I want to handle them as return value, not exceptions

**Comment by nullndr** [comment]
Any news on this?

I'm building a large shopify app and I require to handle throttling according to a [shopify extension](https://shopify.dev/docs/api/usage/rate-limits#graphql-response).

Would love to handle this directly on genql.
