### ISSUE TITLE
Typed useQuery: no warning about incorrect fields in editor under certain circumstances

### ISSUE THREAD

**Issue by dnz-bdeboer** [remorses/genql#127]
Given a typed useQuery (React) of the following format:

```ts
import { QueryGenqlSelection, QueryResult, generateQueryOp } from "./genql"

export function useTypedQuery<Query extends QueryGenqlSelection>(opts: {
  query: Query & { __name?: string }
  pause?: boolean
  requestPolicy?: RequestPolicy
  context?: Partial<OperationContext>
}) {
  const { query, variables } = generateQueryOp(opts.query)
  return useQuery<QueryResult<Query>>({
    ...opts,
    query,
    variables,
  })
}
```

And this graphql schema:

```graphql
type Votes {
  count: Int!
  id: ID!
  what: String!
}

type Query {
  getVotes(what: String!): Votes!
}
```

I can now use this like:

```ts
  const [votes] = useTypedQuery({
    query: {
      getVotes: {
        __args: { what: "my-poll" },
        what: true,
        count: true,
      },
    },
    context,
  })
```

All fine. However, I can type unknown fields in here, for example this does not give an error in my editor:

```ts
  const [votes] = useTypedQuery({
    query: {
      getVotes: {
        __args: { what: "my-poll" },
        what: true,
        count: true,
        hello: "world",  //  <= no type error here in my editor
      },
    },
    context,
  })
```

However, my editor will complain if I write this:

```ts
  const votesSelection: QueryGenqlSelection = {
    getVotes: {
      __args: { what: "my-poll" },
      what: true,
      count: true,
      hello: "world",
    },
  }

  const [votes] = useTypedQuery({
    query: votesSelection,
    context,
  })
```

Which is quite odd, this seems to me the same thing, but perhaps there is some depth of type checking I'm running into?

With editor I mean it doesn't work in VSCodium (VS Code), nor in Emacs (which also uses treesitter).

When I build the app, I get the complaints though, but would like to see them earlier.

Any hints appreciated.

**Comment by xbaun** [comment]
That's just typescript: The generic `Query` extends from `QueryGenqlSelection`, so as long as the declared properties of the type are present, the type shape is fulfilled. Otherwise, if you assign an object to a typed variable and the shape does not macht exactly, that's an error. You can use [`Exact`](https://github.com/sindresorhus/type-fest/blob/main/source/exact.d.ts) from [`type-fest`](https://github.com/sindresorhus/type-fest) to restrict the type.

```ts
export function useTypedQuery<Query extends QueryGenqlSelection>(opts: {
  query: Exact<QueryGenqlSelection, Query>  & { __name?: string }
  pause?: boolean
  requestPolicy?: RequestPolicy,
  context?: Partial<OperationContext>
}) {
  const { query, variables } = generateQueryOp(opts.query)
  return useQuery<QueryResult<Query>>({
    ...opts,
    query,
    variables,
  })
}
```

**Comment by remorses** [comment]
I remember that this problem could be also solved using interfaces instead of types in the generation process but it was becoming too complex so i went with types

**Comment by dnz-bdeboer** [comment]
> That's just typescript: The generic `Query` extends from `QueryGenqlSelection`, so as long as the declared properties of the type are present, the type shape is fulfilled. Otherwise, if you assign an object to a typed variable and the shape does not macht exactly, that's an error. You can use [`Exact`](https://github.com/sindresorhus/type-fest/blob/main/source/exact.d.ts) from [`type-fest`](https://github.com/sindresorhus/type-fest) to restrict the type.

That's a very clear explanation, I'm from the functional world so typescript typing has mysterious properties.

Never heard of type-fest, that's a fantastic tool. And everything now working, thank you so much!
