### ISSUE TITLE
Default Values and Requiredness

### ISSUE THREAD

**Issue by nowlena** [remorses/genql#133]
I'm having an issue with my output types because I have arguments that are "required" but have defaults.

Ultimately, I don't need to pass arguments in my GraphQL query but the genql output types require that I do.

An example:

```gql
input PaginationInput {
  page: Int! = 1
  pageSize: Int! = 25
}
```

will output the following types:

```ts
export interface PaginationInput {page: Scalars['Int'],pageSize: Scalars['Int']}
```

Now in all of my queries that are based on these types I'm being forced to add values even though the defaults exists.

Can these be made optional / not-required when default values exist?

Thanks!

**Comment by remorses** [comment]
Good idea, i will try to implement this soon
