### ISSUE TITLE
Optional types issue with eslint

### ISSUE THREAD

**Issue by jairo-bc** [remorses/genql#134]
Hi!

I got updated genql library from 4.x to 6.x and got some changes in auto-generated files, that leaded to errors from linter.
Changes:
- schema.ts was changed, so optional fields are not optional in typescript anymore. 
example before:
`cart?: (Cart | null)`
example after:
`cart: (Cart | null)`

- typeSelection.ts change
<img width="1208" alt="Screenshot 2023-08-08 at 17 47 24" src="https://github.com/remorses/genql/assets/68893868/26926110-652a-4c0f-a975-bec491f19fae">

Now:
I'm getting  `Unsafe return of an `any` typed value` on something like `cart.items.reduce((acc, item) ...)`

[This](https://github.com/remorses/genql/issues/124) looks pretty similar, but rather removing there `null`, `?` was removed from optional fields.

**Comment by remorses** [comment]
Can you paste the code with the typescript error?
