### ISSUE TITLE
Option to use GET instead of POST for queries

### ISSUE THREAD

**Issue by mmkal** [remorses/genql#135]
Hi, liking genql a lot, it's great!

We are using it for server components within Vercel's app directory, for a graphql backend that supports GET requests like: 

```bash
curl 'https://ourbackend.com/graphql?query=query($foo:String!){abc(slug:$foo){name}}&variables={"foo":"xyz"}'
```

To take full advantage of Vercel's built-in caching, we want to make sure we use GET requests, not POSTs, where possible. We can override either the `fetcher` parameter in `createClient`, or the `fetch` parameter, to achieve this, but neither is ideal. If we pass in a `fetcher` implementation, we need to keep it in sync with the built-in `fetcher` (handle `url` and `headers` ourselves, check the status, call `await res.json()` etc.). But more importantly, I don't think we have a way of knowing for sure that it's actually a `query` that is being requested - and there's a risk that we'll accidentally send a GET for a `mutation`, resulting in caching responses wrongly, and all sorts of other problems. The same problem applies to `fetch`. Maybe `createClient` could allow passing in separate options for operation types, e.g.

```ts
const url = getUrl()
const headers = getHeaders()

export const client = createClient({
  url,
  headers,
  queryOverrides: {
    fetch: async (url, {body, ...options}) => {
      const queryParams = {query: body.query, variables: JSON.stringify(body.variables)}
      fetch(
        `${url}?${new URLSearchParams(queryParams).toString()}`,
        {
          ...options,
          method: 'GET',
        }
      )
    }
  },
})
```

Where the `queryOverrides` options have the same type as the current `ClientOptions`, and are merged in if the operation type is `query`.

**Comment by remorses** [comment]
In this case it’s best to create one client with GET and one with POST for mutations, you will probably want to pass additional caching options like the tags value to be able to revalidate specific queries

**Comment by mmkal** [comment]
Ah ok, do you mean something like this?

```ts
export const createGenqlClient = () => {
  const url = process.env.API_URL + '/graphql'
  const headers = {foo: 'bar'}

  const {query} = genql.createClient({
    url,
    headers,
    fetch: async (resolvedUrl: string, {body, ...options}: RequestInit & {body: string}) => {
      const parsedBody = JSON.parse(body) as {query: string; variables?: {}}
      const queryParams = {
        query: parsedBody.query,
        ...(parsedBody.variables && {variables: JSON.stringify(parsedBody.variables)}),
      }
      return fetch(`${resolvedUrl}?${new URLSearchParams(queryParams).toString()}`, {
        ...options,
        method: 'GET',
      })
    },
  })

  return {
    ...genql.createClient({url, headers}),
    query,
  }
}
```

Good point, that is nicer and avoids worrying about trying to detect queries vs mutations. I don't love that we have to do `JSON.parse(body)`, when it's just been stringified already, it's wasteful. Any ideas on how to avoid that?

**Comment by mmkal** [comment]
@remorses yeah that's essentially what I meant. This does work. Any thoughts on how we could avoid doing a `JSON.parse(...)` on a string that was _just_ `JSON.stringify(...)`d by genql in future?
