### ISSUE TITLE
bug: Exported type alias 'Headers' has or is using private name 'HeadersInit'

### ISSUE THREAD

**Issue by seawatts** [remorses/genql#137]
When generating a genql client with the CLI 
```bash
npx @genql/cli --sort --output ./src/genql --schema ./schema.graphql --esm
```

The file `genql/runtime/createClient.ts` creates a type called `Headers`

```ts
export type Headers =
    | HeadersInit
    | (() => HeadersInit)
    | (() => Promise<HeadersInit>)
```

When running `tsc` on this file, I get the following error:

```
Exported type alias 'Headers' has or is using private name 'HeadersInit'
```

It looks like the code is being generated here: https://github.com/remorses/genql/blob/8c02b9c01ce6d64b900940344b248b18f3d2cc8c/cli/src/runtime/createClient.ts#L9

I believe the fix would be to create a new type for `HeadersInit`. I'm not sure what the type should be which is why I haven't created a PR.

Let me know how I can help here.

**Comment by seawatts** [comment]
Do you have an example of the tsconfig.json file that includes those? I can't seem to get it working.

**Comment by remorses** [comment]
Example tsconfig:
```json
{
  "compilerOptions": {
    
    "lib": ["dom"],
    }
}
```

**Comment by seawatts** [comment]
That worked! Thank you so much. 🙂
