### ISSUE TITLE
Getting "query is not a function" when running a query

### ISSUE THREAD

**Issue by seyaobey-dev** [remorses/genql#145]
I have generated the client by running this command:
`
genql --endpoint https://__my_end__point --output ./generated -H 'Authorization: Bearer myToken'
`
And I have created the client instance with below code:

```
const client = createClient({
    url: "__my_endpoint__",
    headers: {
        "x-hasura-admin-secret": "my_secret",
        "X-Hasura-Role": "admin",
    },
})
```

The first thing I am observing, is that auto-completion is not working: when I write 
```
client.query({
 ..
})
```
I don't get the list of available table names. Then when I execute the query:

```
client.query!({
        users: {
            id: true
        }
    }).then((res: any) => console.log(res));
[app.zip](https://github.com/remorses/genql/files/13403148/app.zip)
[app.zip](https://github.com/remorses/genql/files/13403149/app.zip)

```

I'm getting above error.

I have attached the simple nodejs project with my issue. Thank you for your assistance.

**Comment by coltenkrauter** [comment]
What caused this?
