### ISSUE TITLE
Allow executing against in memory schema

### ISSUE THREAD

**Issue by jasonkuhrt** [remorses/genql#154]
I keep returning to this great library :) Thanks @remorses 

We would like to try genql against an in-memory schema. Not network. Right now the client makes the assumption that the schema will be used over HTTP. We'd like a way to pass in a schema directly instead.

**Comment by jasonkuhrt** [comment]
@remorses Good workaround, makes sense. I still think first class support for direct schema would make sense, it is after all actually simpler and lower level than fetch over network. Bit ironic to override fetch to access the graph in memory :))

**Comment by remorses** [comment]
I am going to keep fetch as most people are already familiar with it, instead of adding another option
