### ISSUE TITLE
RFC: New Genql major version

### ISSUE THREAD

**Issue by remorses** [remorses/genql#161]
New syntax for the client, similar to the [Linear SDK](https://developers.linear.app/docs/sdk/fetching-and-modifying-data), easier to use, even for people not familiar with GraphQL

## Goals: 
- An interface easy for people not familiar with GraphQL
- No more magic fields prefixed with `__` like `__scalar`
- Portable to other programming languages: Python and Go in mind
- Prepare to support directives: #104

## Why?
The plan for genql.dev is to create a service similar to [Stainless](https://www.stainlessapi.com/) where you can generate SDKs for your GraphQL API together with a docs website (something like [this](https://resend.com/docs/api-reference/emails/send-email) but for GraphQL) and a changelog (automatically generated from the schema changes)

Genql generator will remain open source and also have a cli, only the service and the SDK publishing code will be private

> [!IMPORTANT]
> Leave your opinion on the new changes, do you think it's worth a breaking change or not?

### Fetch all scalar fields on a type with no arguments
```ts
const res = await client.getCountries()
```

### Fetch all scalar fields on a type (scalar fields that don't have arguments)
```ts
const res = await client.getCountries({
    args: { name: 'USA' },
})

console.log(countries.map((x) => x.name))
```

### Fetch subdocuments (non scalar fields)

```ts
const res = await client.getCountries({
    args: { name: 'USA' },
    include: {
        regions: true,
    },
})
```

### Fetch subdocuments with arguments

```ts
const res = await client.getCountries({
    args: { name: 'USA' },
    include: {
        regions: {
            args: { name: 'California' },
        },
    },
})

```

### Select only specific scalar fields or fetch scalar field with an argument

```ts
const res = await client.getCountries({
    args: { name: 'USA' },
    select: {
        name: true,
        code: {
            arg: {
                format: 'ISO_ALPHA_2',
            },
        },
    },
})
```

### Select only specific scalar fields

```ts
const res = await client.getCountries({
    args: { name: 'USA' },
   select: {
       name: true
    },
    include: {
        regions: {
            args: { name: 'California' },
        },
    },
})
```

### Fetch an union or interface type

```ts
const res = await client.getNodes({
    onCountry: {
        select: {
            name: true,
        },
    },
    onContinent: {}, // fetch all scalar fields
})
```

If you don't pass `onType` fields Genql will fetch all scalar fields on all possible types

### Fetching many top level fields at the same time

Genql will batch queries done in the same tick. An option will allow you to set a manual batch time in milliseconds

This means that doing the following will batch the queries into a single request:

```ts
const [a, b] = await Promise.all(client.getNodes(), client.getCountries())
```

> [!IMPORTANT]
> Should batch create a single query or use the [Apollo batch protocol](https://www.apollographql.com/docs/router/executing-operations/query-batching/)?

### Mutations

Mutations will be exposed as client top level methods the same way as queries. If a top level mutation has the same name as a query field it will be prefixed with `mutation`, for example `getCountries` will become `mutationGetCountries`

> [!WARNING]
> The same name for both query and mutation should be a very rare case, if you know about any instance of this please add it in the comments below

### Aliases

Aliases are commonly used for
- Fetch the same query in a single request
- Fetch the same field for an union or interface type in different `... on` blocks

These cases are already possible using batching

### Directives

At first directives won't be supported, support will be added later with the following syntax

```ts
const res = await client.getCountries({
    directives: {
        specifiedBy: {
            url: 'https://example.com',
        },
    },
    include: {
        regions: {
            args: { name: 'California' },
        },
    },
})
```

Using this syntax means that directives on arguments won't be supported, does anyone uses them? The only example i know of is `@uppercase` or stuff that modifies the argument, which in an SDK can be done in code

### Get query and variables without executing the request

```ts

import { operationClient } from './generated'

const [{ query, variables }] = operationClient.getCountries()
```

> [!NOTE]
> `operationClient` is not final name, give better ideas

**Comment by jasonkuhrt** [comment]
> Fetch all scalar fields on a type with no arguments

👍 

> Fetch all scalar fields on a type (scalar fields that don't have arguments)

👍 


> Fetch subdocuments (non scalar fields)

👍 

> Fetch subdocuments with arguments

👍 

> Select only specific scalar fields or fetch scalar field with an argument

👍 

> Fetch an union or interface type

👍 

> Should batch create a single query or use the [Apollo batch protocol](https://www.apollographql.com/docs/router/executing-operations/query-batching/)?

Single query would be a good default I would think, gut feeling. Alternative: Simply expose a `client.$batch(client.getY(),client.getX(),...)` method to remove the ambiguity.


> Aliases are commonly used for

Imagine a case where an analytics filtering expression can be given. Then a user might want to get multiple aspects of data analytics in one query.


> These cases are already possible using batching

I don't think this is a great answer to the use-case:

1. User wants to keep a single query response tree to serve their view
2. User may haver aliases deep in a query tree
3. User wants to provide alias names colocated with where that field selection is
4. User wants to make the alias declarative and colocated in one place, not spread out the problem in an ambiguous way (two queries could be for many reasons, and now it could be for aliasing, which is really a weak reason compared to all other reasons for having multiple queries)
