### ISSUE TITLE
query based on condition of a field value

### ISSUE THREAD

**Issue by zmzlois** [remorses/genql#175]
The whole flow of setting up and using it was super convenient! Thank you so much for creating the project!

Wondering if it is possible to create conditional query based on a field's condition?

For example right now I have a query looks like: 

```ts 
const gql = await client1()

    return gql.query({
        templates: {
            __args: { recommended: true, first: 10 },
            __scalar: true,
            edges: {
                node: {
                    __scalar: true,
					metadata: {
						activeProjects: true, // type number
                }
            }

        }
    })

```

I want to limit the query to only query the templates that has activeProjects more than 50, is there any way I can achieve this? 

some example usage like 
```ts
metadata: {

						activeProjects.gt: 50,  // query all activeProjects has number greater than 50
                }
```

**Comment by remorses** [comment]
If your backend API supports this you can filter in the __args object, or you can filter on the returned results

**Comment by zmzlois** [comment]
Unfortunately for this particular API I have no control over the backend, right now I am opting for filtering the returned results

**Comment by remorses** [comment]
No, just filter the returned data
