### ISSUE TITLE
Feature request: silent option for cli

### ISSUE THREAD

**Issue by JustinVoitel** [remorses/genql#19]
Currently when you generate a local client using genql-cli, every single step is getting output to the console. It would be nice if there would be an option like “genql-cli -o client —silent” to disable it or at least turn it into a one-liner output

**Comment by remorses** [comment]
Fixed in latest version, i had `--verbose` true by default

**Comment by MrFoxPro** [comment]
@remorses is it possible to make output more silent? 
![image](https://github.com/remorses/genql/assets/17229619/8afad267-6a3d-40da-aeeb-60b4b8c3c998)
