### ISSUE TITLE
Expose API

### ISSUE THREAD

**Issue by jasonkuhrt** [remorses/genql#21]
We'd like to incorporate genql into Nexus. Ideally though we wouldn't have to spawn to the genql CLI. Mostly because of performance reasons. Adds roughly 1-2s of latency.

**Comment by remorses** [comment]
OK, i will make the last tweaks to the internal API and expose it in the next release

Do you need to also wrap the runtime lib? Can you explain me your use case?

**Comment by jasonkuhrt** [comment]
@remorses I'll loop back here and share a lot more detail once we have our first working prototype.

**Comment by remorses** [comment]
You can now generate a client with
```js
import { generate } from 'genql-cli'
import fs from 'fs'
import path from 'path'

generate({
    schema: fs.readFileSync(path.join(__dirname, 'schema.graphql')).toString(),
    output: path.join(__dirname, 'generated'),
    scalarTypes: {
        MongoID: 'string',
    },
}).catch(console.error)
```

I keep the  issue open for more details
