### ISSUE TITLE
QueryRequest not exported by generated api

### ISSUE THREAD

**Issue by dhmacs** [remorses/genql#22]
The QueryRequest type is not exported as mentioned here in the [docs](https://genql.now.sh/docs/usage/advanced-typings#the-query-fields-type-queryrequest)

**Comment by remorses** [comment]
It's because you are using hasura, hasura changes the name `Query` to `query_root`, so you are searching for `query_rootRequest`

I will addd a type alias

**Comment by remorses** [comment]
added aliases in latest version

**Comment by dhmacs** [comment]
Oh I thought that was a genql type, not tied to the schema. Thanks  👍
