### ISSUE TITLE
Alternative API ("syntax") for graphql argument passing

### ISSUE THREAD

**Issue by jasonkuhrt** [remorses/genql#23]
I was day-dreaming about a nicer way to pass graphql arguments in the API. I realized we could approach GraphQL syntax by leveraging function parameter defaults.

[See the following as TypeScript Playground](https://www.typescriptlang.org/play/index.html#code/PTAEFpIWAKBUDmAnAhgBwBYEcA2oVIIDO+JALgK5o4CmoAtjfQEY1KgCMoAFAMYVIkNAHZlQRAJ5EyTAJSxYWCmwncA3rFCIaZAKpE2ALlABtNaACWAE2MAiDrYA0oKzRppj5lJ9ATjZJGVnAC9jLgBfUEjw5zVwgF1HWHD5GEVlJFUNGC0EHX0jU00tUHNrOwdnV3cfb1Lff0CaELCotpjirWySkpwAe14UMgs+4U9OntBeCzI-U3McFGEEOxFbKMSJrQ6ckp2tTZgUhRglFXVivL0DJGMTCbKbUHsnFzcPerrzOYCg0FDOO0okldl0tqB+oNhqNxqDJtNZo0guD9nsQQcQcc0nAwJBwLB4Mh0Ng8ARiKRQGgCCh6G8AGYoCg4MhEE5nTIAJguuyuBSQ3GsoAAvJwqu9hZ8fD8mi1AdFZKUdlj0ioud1tNdCgKrBKOGL3BKvFKkc1-q15cKAHw8dVaSFDEZjUrghGqRbLCW2NYKuLotHFFKY1Iqznc3L5G7GbW6-VoQ34Y2gX6mgERKIKoXWsO9AYOmHOuFaV0mv3bP2B5LBnGIVCYXD4QgkFAkVwMpliMh9BvkqmoehsjJZS4RtjcMkkEWPMKx2qJ5OytMW32VgfndW8yM8cfx8qit41SX1aV-VNAlJWm0Te3Qp22kqu7juhCe72K0vAgOyIOrzLZjda7dJ0sJ49X3D4jSPEszTldoMyzO9r0dWFJimGZj2aCZUQrI4q3gPECTAWY0BocgMCGfAcH6AB3UAaAAD2oPokAsD0yAwOhGU7Xg+noagdEdWiyF4AA6WiGLYCwRF4GgCMsYRKVQXhhmk0AAGsWJ1Po6STDAWOfPJhHrAy2CGEiTiIugABFxSAr5oOECgWDYABuBpQGYPo+loJZ2nMiRiPEXh2PoFBDWHTV+QmXcHKcpB32qD5rPcd9WDIFAAH5jA8ryaCWYpZGQnMoUdTKCxQ11Su4R8lhWZ41lAAAfZ46SQWw4NAAA3PprAVJrk0wgNGs67qrGSE5YDpChhCUgT2QkLk+mMIggqYFAfSiE48PAUBZOoFBpIwLzXCQE5Jumm9QDm7hhJu8djCWCQTHiAr8GECR6nCIA).

Here's the idea

#### v1 graphql args as tuple member 1 (current system)
```ts
query({
  getUser: [{ id: "1", deep: { a: { y: true, z: 1 } } }, {}],
})

query({
  getUser: [
    { id: "1", deep: { a: { y: true, z: 1 } } },
    {
      location: {
        city: [{ lang: "en" }],
      },
    },
  ],
})

query({
  getUser: [
    { id: "1", deep: { a: { y: true, z: 1 } } },
    {
      location: {
        city: true,
      },
    },
  ],
})
```

#### v2a graphql args as param defaults
```ts
query2({
  getUser(id = 1, deep = { a: { y: true, z: 1 } }) {},
})

query2({
  getUser: (id = 1, deep = { a: { y: true, z: 1 } }) => ({
    location: {
      city(lang = "en") {},
    },
  }),
})

query2({
  getUser: (id = 1, deep = { a: { y: true, z: 1 } }) => ({
    location: {
      city: true,
    },
  }),
})
```

#### v2b graphql args as default to args param

```ts
query({
  getUser(args = { id: 1, deep: { a: { y: true, z: 1 } } }) {},
})

query({
  getUser: (args = { id: 1, deep: { a: { y: true, z: 1 } } }) => ({
    location: {
      city(lang = "en") {},
    },
  }),
})

query({
  getUser: (args = { id: 1, deep: { a: { y: true, z: 1 } } }) => ({
    location: {
      city: true,
    },
  }),
})
```

```ts
// types that allow exploring the autocompletion etc. experience
// in practice kind of thing genql generates

type Deep = { a: { z: number; y: boolean } }

type schema = {
  getUser(
    id: number,
    deep: Deep,
    beta?: boolean
  ): {
    location?: {
      city?: ((lang: "en" | "fr") => void) | true
    }
  } | void
}

function query2(o: schema) {}

// placeholder

function query(...args: any[]): any {}
```

Notes:

- I think the param-default variants are a lot more readable
- writing default parameters get the same autocompletion experience as would passing arguments at a call site
- in GraphQL argument order does not matter, but for v2a it would. I tried writing an overload with all possible combinations of a 3-arg field. The problem is for writing parameter defaults. It is not possible to get autocompletion/type-safety for parameter defaults of overloaded functions. So `genql` would need to pick an order. Any order. But an order. Perhaps matching the order as it is found in the SDL/introspection query would be the best option.
- Another constraint in v2a would be nullable args would have to come after required ones.
- In v2b this constraint is lifted, restoring the arg-giving ordering behaviour of GraphQL. The cost is that we're forced into one level of nesting at all times. And since a lot of GraphQL APIs use the input pattern, it means args with two levels of nesting often... maybe that's a fine tradeoff though! Also it reduces the amount of `=` needed for the developer to enter. And I'm sure that typing `=` in TS to supply values is going to go against typing muscle memory. So minimizing this is a good aspect.
- another advantage of v2b is that it could allow genql to reserve other parameters for other uses. For example, aliases. In the following, `city` field is aliased to `town`:

    ```ts
    query({
      getUser: (args = { id: 1, deep: { a: { y: true, z: 1 } } }) => ({
        location: {
          city(args = { lang: "en" }, alias = "town") {},
        },
      }),
    })
    ```

Criticisms:

- It will have some performance cost since functions need to be executed (but, a build step could transform these calls into an optimized version, perhaps like the genql API today, thus removing the cost)
- when selecting scalars with args, it requires a trailing `{}` rather than just `true` which is ugly and confusing since it looks like the beginning of an object selection.
- finally, this idea is kind of mad 🤷‍♂️ ... but I like it 😅

**Comment by remorses** [comment]
new v3 version is out with a better argument passing syntax with `__args`
