### ISSUE TITLE
Types regression: Field selection not working anymore

### ISSUE THREAD

**Issue by dhmacs** [remorses/genql#24]
The latest version `1.1.21` does not correctly create selected fields types matching the query. The whole type is returned instead. The last working version that I know of is `1.0.58`. See images below

**v1.0.58**
![Screen Shot 2020-07-13 at 09 29 09](https://user-images.githubusercontent.com/4640135/87308092-ff397a80-c51a-11ea-92f3-a4d467cb78a0.png)

**v1.1.21**
![Screen Shot 2020-07-13 at 09 23 03](https://user-images.githubusercontent.com/4640135/87308103-03659800-c51b-11ea-93ad-3921402cce48.png)

**Comment by remorses** [comment]
Now the type selection is done only on the root fields, the previous approach was too complex and the error messages were unreadable, it also slowed down type checks a lot

I had to make a compromise, keep the type selection or simplify type inference

**Comment by dhmacs** [comment]
Mmm this is a big deal, because now it's the developer responsibility to maintain the types, including updating them when the query changes. I can see this lead to a lot of bugs down the road 😬  IMO this approach is equivalent to type query results with `any` since you'll have to maintain the types anyway. 
I think it's kind of a deal breaker because you lose much of the advantage of automated API typescript types

**Comment by remorses** [comment]
The only reason to make the type selection on the result type is to not forget to add the required fields to the query, these bugs are rare because you usually write the query together with the code that consumes it so you know what fields you need

If you want to make sure to have all the fields you can use the `...everything` shortcut

**Comment by dhmacs** [comment]
> you usually write the query together with the code that consumes it

I think this is the case just for straightforward UI. We are building a productivity tool, and I can tell you that same piece of cache is needed in different parts of the UI. Think about for instance optimistic updates. If I need to add a piece of data to a list of items, now all the sudden I have to remember to update all the places where I optimistically update this item list (e.g. the create item page). As the app grows, it gets tricky to remember all the places that you need to update. 
When we updated to the latest version we had ton of typescript errors because every optimistic update was failing. 
On a side note: it seems also that genql types optional fields as required.

> If you want to make sure to have all the fields you can use the ...everything shortcut

Using `...everything` all the time defeats one of the purpose of using GraphQL, that is to require just the data you need to render the UI. This directly impacts performance, especially in an app with complex data requirements and realtime features

**Comment by remorses** [comment]
The graphql fields with non nullable type are required fields in typescript, even on the query type, this is because they are meant to be the return type of the query and not to be used to type the cache

if you want to use them to declare something you can use something like a `DeepPartial` type

**Comment by dhmacs** [comment]
What's the rationale behind this? If the field is optional in the GraphQL schema, what's the benefit of making it required in typescript?
Anyway this probably should be discussed in another issue.

Btw I hope you give a second thought to the typing of the results, or at least type them as `any` or `unknown` so that people don't rely on those types (I don't think it's reasonable to assume that people will always use `...everything` on their queries)

**Comment by dhmacs** [comment]
> The graphql fields with non nullable type are required fields in typescript, even on the query type, this is because they are meant to be the return type of the query and not to be used to type the cache

Oh maybe I understood what you mean here, you mean the required fields that are not selected by the query. But I was referring to fields that are optional in the GraphQL schema. Those fields are still required in the api generated by genql

**Comment by remorses** [comment]
No optional fields should be optional, can you give me a repro?

**Comment by dhmacs** [comment]
I did a couple of tests and this is an issue with the version I'm using `v1.0.58` but has been fixed (latest `v.1.1.21` correctly types optional fields). Unfortunately I won't be able to update because that would break the entire codebase 😅

**Comment by remorses** [comment]
Can you give me an example code of your use case? Why the type change gives you problems?

**Comment by dhmacs** [comment]
After upgrading basically any optimistic update fails. Just one example, here I'm adding a new item to the list, so I optimistically update the react query cache (the cache is typed based on the return type of the genql query):

![Screen Shot 2020-07-14 at 11 25 36](https://user-images.githubusercontent.com/4640135/87409476-4714dc00-c5c5-11ea-8c93-c4ede0046bef.png)

The update fails because not every field fetches the whole type (e.g. `property_values` has other fields that are not needed in the items list). 
Of course you can use `...everything` everywhere, but at the cost of over-fetching, which needlessly impacts performance. Moreover it's even not always possible to handle it this way since certain fields can be accessed only with certain authorizations so effectively the code would break for users without authorization. 
In the end, the only way left is to manually maintaining all the cache types which in turns means that the types returned by genql queries are pretty much useless and not necessarily in sync with manually maintained types.

**Comment by jgoux** [comment]
I agree with @dhmacs , not having strict field selection is a big issue on my end too. When I use TypeScript, I want to use it "all" and reduce as much as I can the runtime errors.

Would you consider adding the typed selection set back behind a `--strict` flag?

**Comment by WonderPanda** [comment]
I just ran into a bug in the app I'm working on where I'd accidentally forgot to include a field as part of a query but the types don't help here so when handling the result I assumed that the value was actually there. I so badly want to use a TS GQL client that allows for fluent and type safe query building but not having safety on the structure of the query result may be a deal breaker for me continuing to use this library. It's a bit more overhead but at this point I'm considering going back to using graphql-code-generator with named GQL operations to get the right type safety.

I've tried a bunch of different tools now including GraphQL Zeus but GenQL seems to have the most potential but this feels like a huge loss to me. Do you think there's anyway that the type inference speed could be fixed or is it a limitation of the current state of TypeScript to be able to consider including this functionality?

**Comment by remorses** [comment]
Now that typescript 4.0 added recursive types support i this has become feasible, previously the code was unreadable and brittle

The problem was that it's difficult to do the type inference from the query to the response is difficult because of the fields that start with the `on_` prefix

I will think of a good way to implement this, stay tuned 😜

**Comment by remorses** [comment]
I also need to wait for [this](https://github.com/microsoft/TypeScript/pull/40336) typescript feature to handle the on_ fields

**Comment by remorses** [comment]
I have published the version 2 packages with different names, try them and let me know of any problem
```
npm i @genql/cli @genql/runtime
```

**Comment by dhmacs** [comment]
@remorses os there an estimated time for when v2 will be stable release? Anyway I'm gonna try to test the 2 packages in the coming week

**Comment by remorses** [comment]
@dhmacs i think i already have implemented all the braking changes, i will wait a week to think if there is anything else i want to change

Write here if there is something you wold like to change to make the lib better so i can take it in consideration

**Comment by dhmacs** [comment]
@remorses sorry for the delay, I'm under a deadline right now, I'll try to get to this asap!
