### ISSUE TITLE
runtime incompatible with vite

### ISSUE THREAD

**Issue by JustinVoitel** [remorses/genql#27]
I've been trying to get my generated client to work in vite (ESM dev tool), but when importing from "./generated/index.esm.js" my app is'nt working, because vite has several problems in resolving some dependencies:

![grafik](https://user-images.githubusercontent.com/30449535/88453957-1c9c0c00-ce6c-11ea-82ee-2582743e5b86.png)

These dependencies unfortunately don't export as esm. 
Is there any way we could get this to work ?

**Comment by remorses** [comment]
You can use the cjs version for now

**Comment by remorses** [comment]
Waiting until the dependencies implement ESM output
https://github.com/zenparsing/zen-observable/issues/62
https://github.com/lodash/lodash/issues/3871

**Comment by remorses** [comment]
Also you shouldn't import from `index.esm` or types won't work, use instead the `--esm` so you can import esm from `./generated` (index.js is an esm module)

**Comment by JustinVoitel** [comment]
Thanks for the clarification 🙏 didn’t knew about the —esm flag, will try out tomorrow..

**Comment by GavinRay97** [comment]
Just as a note -- I tried this with V2 `@genql/cli` and `@genql/runtime`, using `--esm` flag with Vite and it throws this:

Seems to be this one `require()` line for `package.json` throwing a wrench in it

![image](https://user-images.githubusercontent.com/26604994/94372918-a4520100-00cf-11eb-9c92-9c64fd118805.png)

**Comment by remorses** [comment]
i will remove that require and replace it with an import

**Comment by GavinRay97** [comment]
This works now after changes, just as an update :+1:
