### ISSUE TITLE
Add server support with a GraphQL schema

### ISSUE THREAD

**Issue by jferrettiboke** [remorses/genql#28]
Awesome work!

I have a different use case. I wonder if we can get it working for this specific use case.

I am developing [`stripe-graphql`](https://github.com/jferrettiboke/stripe-graphql). A Stripe client for the server. My idea is to generate a NPM package to work on the server. To do so, I would need to pass the GraphQL schema object to `createClient`, instead of `url`.

Is there any way to achieve this right now?

**Comment by remorses** [comment]
You can see an example of the api at #21

**Comment by jferrettiboke** [comment]
I just figured out what I need. It's the `fetcher` in `createClient`.

Thanks anyways.
