### ISSUE TITLE
Feature Request: Sort attributes in generated schema

### ISSUE THREAD

**Issue by ryami333** [remorses/genql#29]
Gidday @remorses, thanks for this product, loving it so far. I like to regularly regenerate and commit the artefacts generated by this tool, and sometimes it produces noisy diffs like this, which are effectively no-ops:

<img width="334" alt="Screenshot 2020-08-11 at 14 00 59" src="https://user-images.githubusercontent.com/12481532/89895035-6b230780-dbdb-11ea-9c51-bd24834837c6.png">

If the order of the attributes of the schema were predictable (sorted alphabetically, for example) then these kinds of diffs would never occur. This sorting could be opt-in (or opt-out) by way of a CLI flag. What are your thoughts?

**Comment by remorses** [comment]
The current order is taken from the schema introspection, popular frameworks like apollo only change the order of the fields only when you change them in your graphql schema, what framework are you using?

I can add a `--sort` flag to sort object properties

**Comment by ryami333** [comment]
The data-source in my current use-case is a Contentful GraphQL API, which is being maintained by another party. I'm not sure how or why they are changing the order of items in the schema, and it's possible that they're not doing it intentionally either. But in any case, the change in order is inconsequential. A `--sort` flag would be perfect for us 👌  Thanks in advance!

**Comment by remorses** [comment]
i implemented the --sort flag, you can test it in the latest version 😊

**Comment by ryami333** [comment]
Nice! That's is _definitely_ an improvement, thank you :)

Two things I've noticed. First, it doesn't seem to work on everything. I just got this diff in `schema.ts`, for example:
```diff
 export interface EntryRequest{
     sys?: SysRequest
-    on_PressModuleItem?: PressModuleItemRequest
-    on_PressModuleBlock?: PressModuleBlockRequest
-    on_MediaSlide?: MediaSlideRequest
-    on_MediaSliderBlock?: MediaSliderBlockRequest
-    on_SellingPointsBlock?: SellingPointsBlockRequest
     on_Page?: PageRequest
     on_AthleteQuotes?: AthleteQuotesRequest
     on_AthleteQuote?: AthleteQuoteRequest
     on_Traits?: TraitsRequest
     on_Strength?: StrengthRequest
     on_BlockStrengthTeaser?: BlockStrengthTeaserRequest
+    on_DescriptionTextBlock?: DescriptionTextBlockRequest
     on_BlockFaqTeaser?: BlockFaqTeaserRequest
     on_FeaturedText?: FeaturedTextRequest
     on_Hero?: HeroRequest
-    on_BlockTestTeaser?: BlockTestTeaserRequest
-    on_BlockWorbRail?: BlockWorbRailRequest
+    on_MediaSliderBlock?: MediaSliderBlockRequest
+    on_MediaSlide?: MediaSlideRequest
+    on_PressModuleBlock?: PressModuleBlockRequest
+    on_PressModuleItem?: PressModuleItemRequest
     on_QuestionsAndAnswersPanelBlock?: QuestionsAndAnswersPanelBlockRequest
     on_QuestionsAndAnswersItem?: QuestionsAndAnswersItemRequest
+    on_SellingPointsBlock?: SellingPointsBlockRequest
     on_TextSectionComponentBlock?: TextSectionComponentBlockRequest
     on_SectionItem?: SectionItemRequest
-    on_DescriptionTextBlock?: DescriptionTextBlockRequest
+    on_BlockTestTeaser?: BlockTestTeaserRequest
+    on_BlockWorbRail?: BlockWorbRailRequest
     __typename?: boolean | number
     __scalar?: boolean | number
 }
```

Second, it doesn't appear to sort union types, so I still get "no-op" diffs like this:
```diff
-export type Entry = PressModuleItem | PressModuleBlock | MediaSlide | MediaSliderBlock | SellingPointsBlock | Page | AthleteQuotes | AthleteQuote | Traits | Strength | BlockStrengthTeaser | BlockFaqTeaser | FeaturedText | Hero | BlockTestTeaser | BlockWorbRail | QuestionsAndAnswersPanelBlock | QuestionsAndAnswersItem | TextSectionComponentBlock | SectionItem | DescriptionTextBlock
+export type Entry = Page | AthleteQuotes | AthleteQuote | Traits | Strength | BlockStrengthTeaser | DescriptionTextBlock | BlockFaqTeaser | FeaturedText | Hero | MediaSliderBlock | MediaSlide | PressModuleBlock | PressModuleItem | QuestionsAndAnswersPanelBlock | QuestionsAndAnswersItem | SellingPointsBlock | TextSectionComponentBlock | SectionItem | BlockTestTeaser | BlockWorbRail
```

**Comment by remorses** [comment]
Ok i added sorting for on_ keys and unions, the only thing that still remains is the `types.json` file

**Comment by ryami333** [comment]
I'm still not seeing union types being sorted consistently, I just got this diff, for example:
```diff
 export type Entry =
-  | ImageSectionModuleBlock
+  | AthleteQuote
+  | AthleteQuotes
   | Page
   | ActivityModuleBlock
   | ActivityModuleItem
-  | AthleteQuotes
-  | AthleteQuote
-  | Strength
-  | Area
-  | StrengthsCardRailBlock
-  | StrengthsHeroHeader
-  | StrengthsCardHeroBlock
   | DescriptionTextBlock
   | BlockFaqTeaser
   | HomeHeaderBlock
+  | ImageSectionModuleBlock
   | InlineQuoteBlock
   | MediaSliderBlock
   | MediaSlide

```

**Comment by remorses** [comment]
Can you try the latest version?

**Comment by ryami333** [comment]
Have been using this option for a couple of weeks with `v1.1.27` and it's exactly what I had hoped it to be, many thanks.

**Comment by ryami333** [comment]
A note for anyone who may stumble upon feature request, and happens to be using the Node API like I am. The flag is called `sortProperties` (rather than just `sort`) in that context. I use it like this:

```js
/* generate-types.js */

require("dotenv/config");
const { generate } = require("genql-cli");
const path = require("path");

generate({
  endpoint: process.env.ENDPOINT_URL,
  headers: {
    Authorization: `Bearer ${process.env.ENDPOINT_TOKEN}`,
  },
  output: path.join(__dirname, "generated"),
  sortProperties: true,
}).catch(console.error);
```
