### ISSUE TITLE
Cannot install genql-runtime

### ISSUE THREAD

**Issue by jasonkuhrt** [remorses/genql#3]
Hey @remorses thanks for building this. I'm one of the core developers of https://nexusjs.org. We might integrate this tool [into ours](https://github.com/graphql-nexus/nexus/issues/1053), I took `genql` for a spin today but got stuck on the following.

1. I followed the cli workflow
2. I generated against a local graphql schema `genql --schema api.graphql --output client`
3. The output resulted in this `client/index.d.ts` module:

	![image](https://user-images.githubusercontent.com/284476/84820680-ffac2780-afe7-11ea-95fc-0828ff728519.png)

4. I wasn't sure if this is normal, as I saw no mention yet of needing to install this dep (missed something?). But I figured I'd try, but then got this error while trying to install:

	![image](https://user-images.githubusercontent.com/284476/84820836-32eeb680-afe8-11ea-855b-4da4f6ebe360.png)

**Comment by remorses** [comment]
Ok there was a `bin` field in the package.json that i forgot to remove

Yarn does not complain about that, this is why i didn't notice it

You can install the latest version

**Comment by jasonkuhrt** [comment]
Ah ok, will use yarn for now. Usually do, just that our examples all use `npm`.

**Comment by remorses** [comment]
the new version is already published, you can use `npm`
