### ISSUE TITLE
Consider migrating generated `types.json` to an exported object in `types.js` for easier build with `tsc`

### ISSUE THREAD

**Issue by GavinRay97** [remorses/genql#31]
Ran into a few hiccups post-compile with Typescript, one was the JS files weren't included by default (fixed with `allowJs: true` easily) but the other was the `types.json` which is read won't get copied into the built output without these settings:
```json5
{
  // Add explicit include for JSON files to copy over "generated/types.json"
  "include": ["./src", "./src/**/*.json"],
  "compilerOptions": {
    // Allow JS to copy the JS files from "generated"
    "allowJs": true,
    // Not sure if this 100% needed but it works
    "resolveJsonModule": true
  }
}
```

If the generated file was a `types.js` like this:
```js
module.exports = {
  // types.json object here
}
```

Then the explicit include and the `resolveJsonModule` wouldn't be required.
Though I am not sure if there are technical limitations or other factors behind current `types.json` implementation.

**Comment by remorses** [comment]
Yeah that’s a good idea, not sure if it is a breaking change
