### ISSUE TITLE
Request: Please publish Changelog or Release Notes

### ISSUE THREAD

**Issue by ryami333** [remorses/genql#33]
Gidday again @remorses, still really enjoying using this package, thanks a lot for it.

There have been quite a few releases over the last couple of weeks, including a "major" version bump, but there is no Changelog, nor are there any Release Notes, so I'm unsure what the new features/bugfixes are, and what backward-incompatible changes have been made (particularly in the case of the major version bump). Could you please annotate the changes in your releases using one of these mechanisms?

Cheers, Mitch.

**Comment by remorses** [comment]
Will do, starting with the major release (still in beta)
