### ISSUE TITLE
Using "headers" with a function seems to only evaluate once, during createClient()

### ISSUE THREAD

**Issue by GavinRay97** [remorses/genql#35]
I'm not sure why this is happening, the below looks like it's set up to evaluate headers function before sending `fetch`:

https://github.com/remorses/genql/blob/dc55320a329e4ac99971b88bda33826be2bf3c00/runtime/src/fetcher.ts#L32-L36

Here's a reproduction, the `headers` function is only invoked once, and you can see from checking `timestamp` header on network requests sent:

https://codesandbox.io/s/wizardly-grass-pzu7s?file=/src/index.ts

Without `headers` invoked per-call, cannot set auth token after signing in for example

**Comment by GavinRay97** [comment]
It turns out you can get around this with a custom fetcher, it's just ugly. Also this doesn't handle multiple query operations I am pretty sure.

```ts
const client = createClient({
  fetcher: async (operation) => {
    const response = await fetch("http://localhost:8080/v1/graphql", {
      body: JSON.stringify({
        query: (operation as any).query,
        variables: (operation as any).variables,
      }),
      method: "POST",
      headers: (() => {
        const headers = {
          "Content-Type": "application/json",
          "X-Hasura-Admin-Secret": "mysecret",
        }
        const authToken = window["authToken"]
        if (authToken) headers["Authorization"] = `Bearer ${authToken}`
        return headers
      })(),
    })

    if (!response.ok) {
      return new Promise((resolve, reject) => {
        response
          .text()
          .then((text) => {
            try {
              reject(JSON.parse(text))
            } catch (err) {
              reject(text)
            }
          })
          .catch(reject)
      })
    }

    const result = await response.json()
    if (result.errors) throw new Error(JSON.stringify(result.errors))
    return result
  },
})

**Comment by remorses** [comment]
Notice that the packages names changes, see https://github.com/remorses/genql/blob/master/CHANGELOG.md

**Comment by GavinRay97** [comment]
@remorses Thank you, as always, for the fix :pray:
