### ISSUE TITLE
Comparsion with gql-zeus

### ISSUE THREAD

**Issue by dodas** [remorses/genql#38]
How does `genql` compare to [`gql-zeus`](https://github.com/graphql-editor/graphql-zeus)?
Seems like they are very similar in what they do.
Any advantages / disadvantages?

Thanks!

**Comment by remorses** [comment]
Graphql Zeus takes an object and outputs a graphql query without varibpables, this means that if you use complex strings as inputs the graphql parser in the server could unexpectedly fail

It also prevents the server from caching queries parsing

Genql instead generates a query with variables, the disatvantage is that you need a representation of your schema in the bundle (in genql this code is in types.js)

**Comment by remorses** [comment]
I will make a comparison table

**Comment by dodas** [comment]
graphql-zeus has support for [variables](https://github.com/graphql-editor/graphql-zeus#variables).

**Comment by remorses** [comment]
Yeah right, i forgot about that, with genql you can just pass the values without explicitly declare variables

**Comment by remorses** [comment]
Released a doc comparing genql to graphql zeus https://genql.now.sh/docs/comparisons/graphql-zeus
