### ISSUE TITLE
Forward heredocs on types in schema to jsDoc on client properties

### ISSUE THREAD

**Issue by jasonkuhrt** [remorses/genql#4]
It would be great if the generated client library included jsDoc based on, in part, the docs in the GraphQL Schema.

For example in the following, we would expect to see "foobar" in the jsdoc:

![image](https://user-images.githubusercontent.com/284476/84824898-9d0a5a00-afee-11ea-9e8c-9d5171b34546.png)

**Comment by remorses** [comment]
This would be a great addition, but before adding too much complexity I want to remove some tech debt

**Comment by jasonkuhrt** [comment]
> maybe i should do the same with the requeust field types?

Yeah I think so

Would you be open to a PR for this?

**Comment by remorses** [comment]
Actually request types already have comments from graphql
