### ISSUE TITLE
Option to Transform Generated Interface Naming Strategy

### ISSUE THREAD

**Issue by WonderPanda** [remorses/genql#42]
The `graphql-codegen/typescript` generates interfaces in Capital Case to be more in line with naming conventions from the community. For example if the GraphQL server had a type called `user` this plugin would generate an interface called `User`.

Would it be possible for genql to also enable changing the interface types naming convention?  For users of Hasura all the GQL types are lower case and there is currently no support to override this naming convention there. I wonder if it would be easier to support it as part of the genql codegen workflow?

I'm willing to help with the implementation effort if this is something that you think could be useful in the code base

**Comment by remorses** [comment]
This is an hard problem because the names used must be converted back to the original schem names, this means i would need to track the original names and use them at the moment of executing the request

I think that it's much better to solve this problem in the hasura schema directly, https://github.com/hasura/graphql-engine/issues/3320

**Comment by WonderPanda** [comment]
Yeah that's understandable. I've been subscribed to the Hasura issue for quite some time but haven't seen much movement there so was wondering if there might be a quick win.

I'd personally be fine with providing both a `from` and `to` mapping function that could be provided to GenQL for this purpose and have it be the developers responsibility to make sure that both are functional so that GenQL wouldn't have to track the original types internally. In most cases running them through the `capitalCase` and `snakeCase` functions from the [change-case library](https://www.npmjs.com/package/change-case) would be sufficient.

I'd still be willing to help make a contribution for this but if you'd rather not clutter this library with extra options I'm fine with that too and can keep waiting for a fix upstream in Hasura

**Comment by remorses** [comment]
Don't try to open a PR for this, it would be too much effort, fixing this in hasura itself would be maybe simpler  🤣
