### ISSUE TITLE
[RFC] Import enums in the browser

### ISSUE THREAD

**Issue by JustinVoitel** [remorses/genql#43]
It would be nice if genql would generate a `object` alongside the `type` definition for enums. This would enable to iterate over enums to easily display them in the browser

1. Lets say I have a schema.graphql that looks something like this
```graphql
...
enum UserRole {
  Admin
  Trusted
  Untrusted
  User
}
...
```

2. Now genql would generate something like this for the enum in schema.ts:
```typescript
...
export const UserRole: {
  Admin: 'Admin',
  User: 'User',
  Trusted: 'Trusted',
  Untrusted: 'Untrusted'
};

export type UserRole = (typeof UserRole)[keyof typeof UserRole]
...
``` 
instead of what its currently doing:
```typescript
export type UserRole = 'Admin' | 'Trusted' | 'Untrusted' | 'User'
```

3. This would enable me to do something like this client-side:
```typescript
let userRole: UserRole = "Admin"

Object.values(UserRole).map(role => {
  console.log(role);
})
```
Very minimal but I hope you get the point ^^

Maybe make this feature configurable so its disabled by default ? 
Please tell me what you think :)

**Comment by remorses** [comment]
Yes this is a good idea, in the meantime you can do this

![1_f0QbU0nW73OubeQlFqDNNA](https://user-images.githubusercontent.com/31321188/105703869-2a5f4680-5f0e-11eb-88a8-ef3f8b15f4af.png)

**Comment by GavinRay97** [comment]
Why about a regular Typescript enum?
It's nearly identical to:
```ts
export const UserRole: {
  Admin: 'Admin',
  User: 'User',
  Trusted: 'Trusted',
  Untrusted: 'Untrusted'
};

export type UserRole = (typeof UserRole)[keyof typeof UserRole]
```
![image](https://user-images.githubusercontent.com/26604994/107263442-bf366980-6a0f-11eb-8354-757f5898aed6.png)
