### ISSUE TITLE
Selection set static type error 

### ISSUE THREAD

**Issue by jasonkuhrt** [remorses/genql#47]
When extracting a selection set the inferred type is changed. This fails to type check but should work. Note how `workspaces` IS part of the selection set.

![image](https://user-images.githubusercontent.com/284476/107600948-46900280-6bf3-11eb-8044-f6ea397aa35d.png)

Now, if we inline the selection set, then we can access the `.workspaces` field on the result as expected:

![image](https://user-images.githubusercontent.com/284476/107600985-61fb0d80-6bf3-11eb-8bf9-40f87c88f6d9.png)

**Comment by jasonkuhrt** [comment]
Here is a simpler repro:

![image](https://user-images.githubusercontent.com/284476/107601185-f7969d00-6bf3-11eb-9cf5-8f22de761dec.png)

**Comment by jasonkuhrt** [comment]
Interesting... If I remove the `QueryRequest` type the later type errors go away and things work as expected:

![image](https://user-images.githubusercontent.com/284476/107601301-4c3a1800-6bf4-11eb-9d14-67847d839c51.png)

The downside here is that now there is no intellisense for the selection set definition (autocomplete etc.)

**Comment by jasonkuhrt** [comment]
This is actually noted in the docs already: 

> Notice that when using QueryResult you cannot use the QueryRequest type on the fields object because you would lose the selected fields type

Although, tbh, I don't really understand what the issue is and why this _must_ be the case. I would imagine it is possible to have best of both worlds with TS here... 🤔

**Comment by remorses** [comment]
Yes the problem is that typescript looses type information if you add the request type declaration (`QueryRequest`)

To have the best of both worlds you will need to create a wrapper function so that you don't need to declare the request in a different variable

Example is [here](https://github.com/remorses/genql/blob/master/example-usage/pages/apollo-wrapper.tsx#L14)
