### ISSUE TITLE
Bug - Can't get typing of raw query when the field is an array

### ISSUE THREAD

**Issue by Newbie012** [remorses/genql#49]
If we take a look at this example:

https://github.com/remorses/genql/blob/9dda8692238c256709a1fe196e04c82b419eeba3/example-usage/pages/apollo.tsx#L10-L19

then it looks like we get the typing by `<QueryResult<typeof q>>` which works great in this example.

But If we change the query to something like (according to https://genql.now.sh/docs/usage/usage-with-other-clients):

```ts
 const q = { 
     countries: [
        { argument: 'exampleArgument' },
        { 
           name: true, 
           code: 1, 
         }
     ] as const, 
 }
```

We get an an error:

```
The type 'readonly [{}, { readonly name: true; code: 1 }]' is 'readonly' and cannot be assigned to the mutable type ...
```

Is there a typescript flag that I should've changed?

---

### A more specific error (based on my code):
![image](https://user-images.githubusercontent.com/10504365/108496571-e9f7ac00-72b2-11eb-9f64-3743cd2e6696.png)

**Comment by remorses** [comment]
Typescript complains because it seems that readonly stuff is not assignable to mutable types now

A solution would be to use a `tuple` function that makes a tuple type from an array (that was the `as const` was doing)

```ts
function tuple<T1, T2>(data: [T1, T2]): typeof data
function tuple(data: Array<any>) {
    return data
}

 const q = { 
     countries: tuple([
        { argument: 'exampleArgument' },
        { 
           name: true, 
           code: 1, 
         }
     ]), 
 }

```

I could generate this function in the client code for better reuse

**Comment by Newbie012** [comment]
Woah that was fast. Thanks! seems to work now.
