### ISSUE TITLE
Suggestion - Get the query operation type while maintaining the autocompletion

### ISSUE THREAD

**Issue by Newbie012** [remorses/genql#50]
This issue is about advanced typing - https://genql.now.sh/docs/usage/advanced-typings

Given the following code:

```ts
// based on the issue https://github.com/remorses/genql/issues/49
function tuple<T1, T2>(data: [T1, T2]): typeof data
function tuple(data: Array<any>) {
    return data
}

const q = {
    advertisers: tuple([
        { skip: 1},
        { isActive: true }
    ])
};

const { query, variables} = generateQueryOp(q);
const { data, error} = useQuery<QueryResult<typeof q>>(gql(query), { variables: variables });
```

Everything will work as expected. I can't mistype and the type of the data will be correct. Although, there's one disadvantage with this approach.

Since `q` isn't explicitly typed, we lose the ability to autocomplete (although if we mistype something, the compiler will complain).

Is there a way we could dance at two weddings by both having the data typed and having the autocompletion?

**Comment by remorses** [comment]
Unfortunately this is a typescript limitation, you can’t have bot because this way you would lose the selected fields information

the best thing you can do is create a wrapper around useQuery so that you don’t have to create a separate variable for query

**Comment by remorses** [comment]
Made an example here 
https://github.com/remorses/genql/blob/c0bc0250f79dea5e8064f84f44bbc689648ade07/example-usage/pages/apollo-wrapper.tsx

**Comment by Newbie012** [comment]
Amazing. works like a charm!
