### ISSUE TITLE
Incorrect __typename type

### ISSUE THREAD

**Issue by jasonkuhrt** [remorses/genql#51]
In the following, `__typename` should be possibly `undefined`.

![image](https://user-images.githubusercontent.com/284476/109809646-8ea0b480-7bf6-11eb-84ee-0027e2bbe501.png)

**Comment by remorses** [comment]
For me querying `{  __typename }` returns `{ "__typename": "Query" }`

Do you mean it should be always defined?

**Comment by jasonkuhrt** [comment]
> Do you mean it should be always defined?

Yep!

**Comment by jasonkuhrt** [comment]
Are you open for a PR for this? It breaks our ability to discriminate properly.

![image](https://user-images.githubusercontent.com/284476/112237933-0ff9ce80-8c1a-11eb-8757-d632cc48c7ff.png)


The `?` on the key makes it so an upper level `=== undefined` check still isn't good enough to make TS narrow the type.

**Comment by remorses** [comment]
Tell me if i understood correctly, you want the `__typename` field to be `Type` instead of `Type | undefined` when you are explicitly querying `__typename`, is this right?

**Comment by jasonkuhrt** [comment]
Yeah
