### ISSUE TITLE
Per-request headers

### ISSUE THREAD

**Issue by jasonkuhrt** [remorses/genql#53]
It is possible to setup headers at construction time, but not possible to set headers for a particular request.

It is possible to work around this by wrapping Genql with a function that creates an instance anew for each request, but obviously not ideal.

```ts
type EnhancedGenqlClient = {
  mutation<R extends Genql.MutationRequest>(
    request: R & { __name?: string },
    config?: { headers?: Record<string, string> }
  ): Promise<GenqlRuntime.FieldsSelection<Genql.Mutation, R>>
  query<R extends Genql.QueryRequest>(
    request: R & { __name?: string },
    config?: { headers?: Record<string, string> }
  ): Promise<GenqlRuntime.FieldsSelection<Genql.Query, R>>
}
```
```ts
  const enhancedGenql: EnhancedGenqlClient = {
    mutation(selectionSet, config) {
      const genql = Genql.createClient({
        url: `http://localhost:${serverPort}/api/graphql`,
        headers: {
          Authorization: `Bearer ${token}`,
          ...config?.headers,
        },
      })
      return genql.mutation(selectionSet)
    },
    query(selectionSet, config) {
      const genql = Genql.createClient({
        url: `http://localhost:${serverPort}/api/graphql`,
        headers: {
          Authorization: `Bearer ${token}`,
          ...config?.headers,
        },
      })
      return genql.query(selectionSet)
    },
  }
```

Open to a pull-request for this?

Thanks!

**Comment by remorses** [comment]
I was thinking something like this, would this work for you?

```ts
import { createClient } from './generated_dir'

const client = createClient({
    url: 'http://your-api',
    headers: ({ isQuery, isMutation }) => ({
        Authorization: isMutation ? localStorage.get('authToken') : '',
    }),
})
```

**Comment by jasonkuhrt** [comment]
That's nice.

Our use-case is to supply a header to the server based on the test title.

Either of the following could work. The former looks more appealing generally.

```ts
client.configure({ headers }).mutation()
client.mutation({}, { headers })
```

**Comment by remorses** [comment]
You can already do that,
 you can already pass a function to the headers option

```ts
import { createClient } from './generated_dir'

let testName

const client = createClient({
    url: 'http://your-api',
    headers: () => ({
        SourceTest: testName,
    }),
})


describe(`test`, () => {
  test('test', async () => {
     testName = expect.getState().currentTestName
     await client.mutation(...)
  });
});



```

**Comment by jasonkuhrt** [comment]
@remorses Sure, but a lot of things are possible via closures and lexical scope. It can lead to greater complexity via indirection.

Anyways we happen to be using `jest.each` and the test code and the headers definition are actually in separate modules. I think your solution works for some cases of course.

**Comment by GavinRay97** [comment]
I would also find this feature useful FWIW

Obviously in most cases you can work around it, by making the function for headers read from state outside of itself. 

But it would be really nice to contextually be able to pass a specific header object on a case-by-case basis (same for mutations).

**Comment by remorses** [comment]
This is not very possible to implement now because the batching library i am using does not let me do that,

**Comment by jgoux** [comment]
Hey @GavinRay97, you must think about Hasura's use case? We're in the same boat, we need to send a `x-hasura-role` per request. We use the createClient() trick currently but it's not that convenient.
