### ISSUE TITLE
Support for GraphQL aliases take 2

### ISSUE THREAD

**Issue by jasonkuhrt** [remorses/genql#55]
I thought I had a use-case for https://github.com/remorses/genql/issues/10  but then didn't. Still interested in having aliases supported though.

I can't remember right now but if we can make the types "extensible" (records with known fields) then we could treat ANY UNKNOWN key as being an alias. Its type would be a union of objects for each peer field, where each [object accepts ONLY ONE](https://stackoverflow.com/questions/62158066/typescript-type-where-an-object-consists-of-exactly-a-single-property-of-a-set-o).

```ts
{
  things: [ 
    {}, 
    {
      foo: true,
      foo2: { foo: true },
      bar2: { bar: { /* selection set */ } },
      qux2: { qux: [{/* args */},{ /* selection set */ }]}
    }
  ]
}
```

> I can't remember right now but if we can make the types "extensible" (records with known fields) then we could treat ANY UNKNOWN key as being an alias.

If not, then, unfortunately:

```ts
{
  things: [ 
    {},
    {
      foo: true,
    }, 
    {      
      foo2: { foo: true },
      bar2: { bar: { /* selection set */ } },
      qux2: { qux: [{/* args */},{ /* selection set */ }]}
    }
  ]
}
```

I am pretty sure that what will happen is the record's known fields vs extensible ones will have to share the same type, and that is NOT what we want here. Thus, a third parameter would be needed.

**Comment by remorses** [comment]
The problem of doing aliases is that typing becomes a nightmare, as you can see [the current type for fields selection](https://github.com/remorses/genql/blob/master/runtime/src/client/typeSelection.ts)  is already very complex, adding more will make type checking and completion slower and probably create new bugs

**Comment by jasonkuhrt** [comment]
Yeah I believe that. I think type tests might be able to help with regard to testing. Here is a minor example of some we did in Nexus https://github.com/graphql-nexus/nexus/blob/main/src/typegenTypeHelpers.spec.types.ts.

I'm not sure how applicable that is here though.

**Comment by remorses** [comment]
I already do test types 👍

What i am saying is that the alias feature is not worth the additional complexity

**Comment by thelinuxlich** [comment]
BTW Zeus supports aliases: https://github.com/graphql-editor/graphql-zeus#perform-query-with-aliases

**Comment by jasonkuhrt** [comment]
Aliases are needed to workaround this weird issue https://github.com/graphql/graphql-js/issues/522. I am not fully convinced/understand it but alas it seems like a GQL limitation that will not be going away.

**Comment by thdxr** [comment]
are aliases planned at all? we're trying to figure out if we should use genql or zeus and it'll likely be the deciding factor

**Comment by jasonkuhrt** [comment]
Another use-case for aliases. We need to fetch workspace usage twice, for the current and the previous cycle. This seems like a perfect use-case of aliases:

![CleanShot 2023-12-06 at 12 41 19@2x](https://github.com/remorses/genql/assets/284476/e08a4e79-a576-4ba5-9961-82e421c73f18)

For the time being, batching offers a workaround: https://genql.dev/docs/usage/batching-queries, but I don't consider it ideal.
