### ISSUE TITLE
Fetch all the field when no argument is given to .get()

### ISSUE THREAD

**Issue by jgoux** [remorses/genql#56]
Hello 👋,

We're using genql for our integration tests against our GraphQL API, it's a real pleasure to use, awesome work @remorses !

We were wondering if we could have an extra option option to the generate command to automatically have `{ __scalar: true }` as the default value when using the chain syntax and calling `.get()`.

I totally understand the choice to be explicit on the client-side about the fields, but when we are in a backend context, it adds noise to the code.

```diff
const [userConnection, userLocation] = await Promise.all([
        genql.chain.query
          .user_connections({
            where: { user_id: { _eq: existingUser.id } },
          })
-          .get({ __scalar: true }),
+         .get(),
        genql.chain.query
          .user_locations({
            where: { user_id: { _eq: existingUser.id } },
          })
-          .get({ __scalar: true }),
+         .get(),
      ]);
```

**Comment by remorses** [comment]
v3 no longer has chain syntax
