### ISSUE TITLE
Error handling with runtime fetcher

### ISSUE THREAD

**Issue by ejkkan** [remorses/genql#60]
The "createFetcher" function swallows everything and return a string in case of an rest error.
https://github.com/remorses/genql/blob/0d5aadb9e2583ed458ba948a6b4e025e51b62435/runtime/src/fetcher.ts#L46

For example. right now I can't reach the error status code for a requests the outputs an error. 

I think that it would be better to just throw the entire Error and let the user handle it themself to not enforce this very narrow information output.

**Comment by remorses** [comment]
The best way to get access to the status code is using a customer `fetcher` or `fetch` function
