### ISSUE TITLE
Closed connections in a test suite

### ISSUE THREAD

**Issue by fbonhomm** [remorses/genql#62]
Hello,

I use your library for my test suite with jest.

Jest creates a process for each test and I have a memory leak and running processes.

I think that closing the GenQl client connection for each test could solve the problem.

Is there any way to close the client connection?

Thank you.

**Comment by remorses** [comment]
Are you using subscriptions?

**Comment by fbonhomm** [comment]
Yes, I use Queries, Mutations and Subscriptions

**Comment by remorses** [comment]
You. We’d to unsubscribe and close the client, like I did here https://github.com/remorses/genql/blob/e624743b99278e8346fa7154369fe03b35b1a5fc/integration-tests/tests/execution.ts#L652

**Comment by fbonhomm** [comment]
Ok thanks
