### ISSUE TITLE
Generate object literals for enums

### ISSUE THREAD

**Issue by jasonkuhrt** [remorses/genql#64]
We're currently rolling out this pattern. 

```ts
export * from '@genql/client'
import type { PlanetscaleRegion as PlanetscaleRegion_ } from '@genql/client'

export type PlanetscaleRegion = PlanetscaleRegion_

// TODO get object literals for enums from Genql core.
export const PlanetscaleRegion = {
  us_east: 'us_east',
  us_west: 'us_west',
  ap_northeast: 'ap_northeast',
  ap_south: 'ap_south',
  ap_southeast: 'ap_southeast',
  eu_west: 'eu_west',
} as const

```

This is so that frontend code can create enum members and more (such as create zod schema types based on the enum for frontend form validation).

It would be great to have Genql ship (generate) these object literals by default.

**Comment by remorses** [comment]
I am gonna use a different name for the new constant object, would `mapToEnumName` be a good name?

```ts
export const mapToPlanetscaleRegion = {
  us_east: 'us_east',
  us_west: 'us_west',
  ap_northeast: 'ap_northeast',
  ap_south: 'ap_south',
  ap_southeast: 'ap_southeast',
  eu_west: 'eu_west',
} as const
```

**Comment by jasonkuhrt** [comment]
I think I get that, its a map of identifiers to enum names (the values). Not sure its my favourite but subjective somewhat.

Some considerations:

- If we just match the type name then it means there's only one name to "think about". In type position it is a union and in term position it is an object (and getting the union is trivial like this: `Object.values(<EnumName>)`.
- Prisma takes this approach fwiw (just some precedent/thinking in this area to maybe borrow from)

**Comment by jasonkuhrt** [comment]
If we do go with a name that is different than the type name, do we want to centralize this but co-locating with the domain category or centralizing on the function category?


```
mapToEnumName    -- group by function
EnumNameMap      -- group by domain
```

**Comment by remorses** [comment]
I think group by function is better: this way the name would start with lower case letter, which makes it different from a type name that is usually capitalized

**Comment by jasonkuhrt** [comment]
@remorses good enough for us! Left some subjective thoughts above about naming but mostly important here is having the data period so whatever you think is best ultimately!

**Comment by jasonkuhrt** [comment]
If you can allow a way to customize this in the CLI that would be ideal :)

**Comment by remorses** [comment]
You can now import `enumPlanetscaleRegion` and do `enumPlanetscaleRegion. us_west `
