### ISSUE TITLE
generated enum terms have string type values

### ISSUE THREAD

**Issue by jasonkuhrt** [remorses/genql#65]
<img width="396" alt="CleanShot 2021-11-02 at 14 46 25@2x" src="https://user-images.githubusercontent.com/284476/139926303-1495af9c-526e-443b-b3a6-a33d153f0064.png">

I don't see any good reason to not tighten up the types here. One issue is that in TS the stdlib typings are such that `Object.keys` returns `string[]` while `Object.values` will return a union of the values. Thus, out of the box, what Genql generates isn't quite optimal.

**Comment by jasonkuhrt** [comment]
Another reason is for sites where the string literal is required 
<img width="484" alt="CleanShot 2021-11-02 at 14 49 43@2x" src="https://user-images.githubusercontent.com/284476/139926855-398d4ed3-32a8-497a-ac06-ea846f7de174.png">

**Comment by remorses** [comment]
Thank you for the report, Fixed in 2.8.0
