### ISSUE TITLE
How do we handle directives with genql?

### ISSUE THREAD

**Issue by thelinuxlich** [remorses/genql#66]
I don't see any example with it!

**Comment by remorses** [comment]
There is no support for directives, honestly i can't really think of a good way to implement them in an object like syntax 🤔

Also, i never used directives in queries, what is your use case?

**Comment by thelinuxlich** [comment]
There are some client-side libraries using directives, example: https://apis.guru/graphql-lodash/

**Comment by joshua1** [comment]
@remorses  is this possible with genql now ?

**Comment by betabong** [comment]
e.g. Shopify uses this to select the language: https://shopify.dev/changelog/storefront-api-incontext-directive-supports-languages

As of now @thelinuxlich 's proposition got not implemented – and I don't see how we can work around it. Which is a stopper. Does anybody see how this could be achieved?

**Comment by bennyk8y** [comment]
A must feature from my side. Simple and basic stuff like 
https://the-guild.dev/graphql/tools/docs/schema-directives#formatting-date-strings (date transform directive) 

are not feasible to use...it kinda a deal breaker

**Comment by remorses** [comment]
Moved to https://github.com/remorses/genql/issues/104
