### ISSUE TITLE
A 'const' initializer in an ambient context must be a string or numeric literal or literal enum reference

### ISSUE THREAD

**Issue by seyaobey-dev** [remorses/genql#68]
In my `nest.js` application, I have generated a client SDK from a graphql endpoint. But now when I start the app, in debug mode,
I get typescript yelling at me with the above error. The above error comes from the generated `index.d.ts`. For example, this is the first time (of many) block code where the error is first encountered:

```
export declare const enumauthAccountProvidersConstraint = { // <-- error thrown from here
  account_providers_account_id_auth_provider_key:
    'account_providers_account_id_auth_provider_key',
  account_providers_auth_provider_auth_provider_unique_id_key:
    'account_providers_auth_provider_auth_provider_unique_id_key',
  account_providers_pkey: 'account_providers_pkey',
} as const
``` 

```
"@genql/cli": "^2.8.0",
"@genql/runtime": "^2.8.0",
"typescript": "^4.2.3"
```

**Comment by seyaobey-dev** [comment]
After having compared my `tsconfig.json` with the one from the `example-usage` folder, I have added `"skipLibCheck": true` to my `tsconfig.json`. This has made the error to go away. But now when I attempt to start and run my `nest.js` app, I get the following error:

```
internal/modules/cjs/loader.js:905
  throw err;
 ...
     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
 ...
code: 'MODULE_NOT_FOUND',
```

If I remove the flag `skipLibCheck`, the above error goes away but then I get back to the `const` error from the generated `index.d.ts` file from `genql`

**Comment by remorses** [comment]
You didn’t paste the full error, however it is probably not related to genql

**Comment by seyaobey-dev** [comment]
Thanks for the reply. So I just created a new project from scratch since I could not figure out why typescript was yelling at me. This fixed the typescript error. So I'll just close this ticket. Thanks for the library. I was using [this tool](https://www.graphql-code-generator.com/). But as the number of graphql operations increases, it becomes cumbersome 
to define a query in a `.graphql` file and run the cli-tool to generate the sdk.
