### ISSUE TITLE
Generate SDK from authenticated endpoint

### ISSUE THREAD

**Issue by dhmacs** [remorses/genql#7]
There's no mention in the docs on how you can generate the SDK from an authenticated endpoint (e.g. Hasura with admin secret).. The help command of the CLI shows that there's some config, where can I find how to setup the authentication header during generation?

By the way this is a really cool project 👏 👏

**Comment by remorses** [comment]
I added the header option

```
genql --endpoint https://countries.trevorblades.com --out ./generated -H 'Autorization: Bearer myToken'
```

You can pass multiple values repeating the flag

**Comment by dhmacs** [comment]
@remorses I think it makes sense when using Hasura. You are essentially creating multiple endpoint apis based on the user (e.g. admin, user, public) and you might not want to publicly expose details about your tables that should only be visible to admins.

I usually generate the SDK using dev credentials and I keep it under version control. So there's no need to use production secrets
