### ISSUE TITLE
Connection Error handling

### ISSUE THREAD

**Issue by boredland** [remorses/genql#72]
Hi there! tyvm for this nice library! ❤️ 

I am very new to genql, so perhaps I am using it wrong. I just saw the following behavior:

My gql api has not been reachable on the given `url`. The client did just not return. So execution stopped, without any feedback or throwing an error. shouldn't it at least log an error? How about retry behavior (didn't test that,  but didn't find anything in the docs)?

**Comment by remorses** [comment]
you can pass an `AbortController` signal to the client to make fetch stop after a timeout
