### ISSUE TITLE
subscriptions not working consistently

### ISSUE THREAD

**Issue by seyaobey-dev** [remorses/genql#78]
I have a subscription which does not work consistently. Sometimes, randomly, it just stops working: in other word, it does not resolve. e.g:
```
genqClient.subscription({
  users: [
  {
     where: {
        email: {
           _eq: 'xxx',
        } 
     }  
  }, 
  {
     id: true,
     ... 
  }],
}).subscribe((result) => { // <-- this is not called
  ...
});
```
It works 90% of times, then it just stops working. But when I use `apollo-client`, it works consistently (but I don't want to revert to apollo-client, too much boiler-plate). It seems also to work fine on android, but fails sometimes on ios.

```
"@genql/runtime": "^2.8.0",
"@genql/cli": "^2.8.0",

react-native: 64;
expo: 44;
ios: 15.1
```

**Comment by remorses** [comment]
v3 no longer supports subscriptions
