### ISSUE TITLE
Error on parsing schemas with custom directives and scalars

### ISSUE THREAD

**Issue by nikodevv** [remorses/genql#79]
We have an amplify project that relies on [aws directives](https://docs.amplify.aws/cli-legacy/graphql-transformer/directives/) and scalars that are not part of graphql spec. In setup of genql we encounter the following error

```
genql --schema ./schema.graphql  --output ./generated
Unknown directive "@function".
Unknown directive "@aws_iam".
Unknown directive "@aws_cognito_user_pools".
    at assertValidSDL (node_modules/graphql/validation/validate.js:135:11)
    at Object.buildASTSchema (node_modules/graphql/utilities/buildASTSchema.js:44:34)
    at makeSchema (node_modules/@graphql-tools/merge/index.js:1159:99)
    at Object.mergeSchemasAsync (@graphql-tools/merge/index.js:1153:12)
    at async Object.loadSchema (@graphql-tools/load/index.cjs.js:651:20)
```

There doesn't seem to be an easy way around this. Is there a desire from the project to support custom directives/let users extend grapghql specs?

**Comment by remorses** [comment]
should be fixed in v3

**Comment by alexeypolitov** [comment]
Looks like it not supported in newest `"@genql/cli": "^6.0.0`.

```

[FAILED] Unknown directive "@aws_cognito_user_pools".

[FAILED] Unknown directive "@aws_api_key".

[FAILED] Unknown directive "@aws_cognito_user_pools".

[FAILED] Unknown directive "@aws_api_key".

[FAILED] Unknown directive "@aws_cognito_user_pools".

Success! Generated client code inside './generated'
```

Nothing generated in './generated'

**Comment by remorses** [comment]
This is an issue with AWS amplify, it does not declare the directives, you can fix it by adding the directives to your schema manually 

The aws directive are these:
https://github.com/lazpavel/amplify-cli/blob/5d963c0abc2c6cf0b029ad0e1e15344f27c83827/packages/amplify-graphql-transformer-core/src/transformation/validation.ts#L109
