### ISSUE TITLE
ts errors in schema.ts

### ISSUE THREAD

**Issue by samburgers** [remorses/genql#81]
Hi there, getting a few errors in the generated `schema.ts` file... from a bare bones Statamic graphql endpoint. 

```
export type PageInterface = () & { __isUnion?: true }
---
'=>' expected.ts(1005)
```
And a bunch more errors summarized here:

<img width="695" alt="Screen Shot 2022-04-10 at 9 30 22 am" src="https://user-images.githubusercontent.com/1476939/162594852-9d3e5bad-ae89-4f8c-9c01-ac05425fd8e3.png">

Any thoughts? I can provide the schema file in full if thats helpful. Thanks!

**Comment by remorses** [comment]
Can you paste the full schema.ts file? If too big you can use a gist and link it here

**Comment by samburgers** [comment]
Sure thing here you go. Thanks!

https://gist.github.com/samburgers/717cec5c385ffc67cf979fbbb0638916

**Comment by remorses** [comment]
Can you paste also the graphql schema file?

**Comment by samburgers** [comment]
yep here it is 

https://gist.github.com/samburgers/378f2635f084e334f08e352b5d360e76

**Comment by remorses** [comment]
The problem was with interfaces without any implementations

**Comment by samburgers** [comment]
Thanks so much for looking into it. Incredible lib you have built here 🤩
