### ISSUE TITLE
Query string support

### ISSUE THREAD

**Issue by samburgers** [remorses/genql#84]
Hi, I am interfacing with a graphql client (Statamic/Laravel) that supports "preview mode" by way of a query string

Standard request
`http://myapi.com/graphql`

Preview mode request
`http://myapi.com/graphql?token=123456`

would it be possible to add these params without needing to redefine the url?, similar to how you can with headers

was thinking something like this would be possible, but it doesnt appear to be the case. thanks!

```
createClient({ params: { token: "1234" } })
```

**Comment by remorses** [comment]
You can use a custom fetcher: https://genql.vercel.app/docs/usage/create-the-client#using-a-custom-fetcher

**Comment by samburgers** [comment]
thanks @remorses , for my situation i am trying to include some additional confidence that the endpoint is the same as the one that was used for the `generate` command

custom fetcher would totally work, i wonder would it be possible perhaps to include the endpoint in the generated exports so something like this was possible?

```
import { createClient, endpoint } from './generated_dir'

const client = createClient({
    url: `${endpoint}?token=${myToken}`,
})
```

thanks again!

**Comment by remorses** [comment]
you can pass the url to the client with any query string you want but it must be an absolute url
