### ISSUE TITLE
omitting wsClient from being bundled when not used

### ISSUE THREAD

**Issue by boredland** [remorses/genql#89]
I don't use the wsClient and don't plan to use it - nevertheless it ends up in my bundle.

Has anyone got an idea how I can make it tree-shakeable in this [case](https://github.com/ioki-mobility/transitland-gql-client/blob/main/src/index.ts#L17)?

**Comment by remorses** [comment]
Currently It's not tree shakeable, in the next breaking change i will separate the subscription client so you can remove it from the bundle

**Comment by boredland** [comment]
thats great news! Thanks for all your work! :muscle:

**Comment by remorses** [comment]
v3 no longer has subscriptions so bundle is smaller

In the future if subscriptions will be added it will be with a different import like `createSubscriptionClient`
