### ISSUE TITLE
Feature request: Batching operations

### ISSUE THREAD

**Issue by dhmacs** [remorses/genql#9]
GraphQL API supports batched operations (e.g. [Hasura](https://hasura.io/docs/1.0/graphql/manual/api-reference/graphql-api/index.html#batching-operations)). 

This would be really really useful (especially for large interactive apps). Apollo implements it via the [batch http link](https://www.apollographql.com/docs/link/links/batch-http/). 

I think it would be awesome if this was supported directly by genql as a config, but another viable solution could be to expose the fetcher.

**Comment by remorses** [comment]
You can get the benefits of type safety and type completion using other clients following [this doc](https://genql.now.sh/docs/usage/usage-with-other-clients) (there i use genql with apollo)

I don't want to build too many features into the built in client, it is not the aim of this library

**Comment by dhmacs** [comment]
@remorses We're 90% done with migrating a big project from Apollo to React Query 😅 We're using `graphql-request` as the fetcher and have all operations types generated with GraphQL codegen. The main reason we are experimenting with genql is because we have many dynamic queries. 
Would you consider exposing the fetcher as a `createClient` argument so we can customize the behavior?

**Comment by remorses** [comment]
Ok i can expose the fetcher, can you show my an API interface you would like to have?

**Comment by dhmacs** [comment]
I think we just need to be able to switch `createFetch` function with a custom one:
https://github.com/remorses/genql/blob/03c0f1a6ab042b0397963124e2a37385519b97f9/genql-runtime/src/fetcher.ts#L13-L47

The API could look like this:

```typescript
createClient({
  url: ..,
  headers: { Authorization: "Bearer myToken" },
  fetcher: options => async (operation) => {
     // Custom implementation that returns result or throws an Error
  }
});
```

So the type of the custom fetcher would be like:
```typescript

type Fetcher =  (options: Options) => (operation: GraphqlOperation) => Promise<any>

type Options = {
    url?: string
    headers?: Headers
} & Omit<RequestInit, 'headers'>;
```

**Comment by remorses** [comment]
I added the custom fetcher, the type is simpler
`(operation: {query, variables}) => Promise<{data, errors}>`

I made a guide on how to batch queries [here](https://genql.now.sh/docs/usage/batching-queries)

**Comment by remorses** [comment]
If you find a good batching library that is still maintained and has typeings i can add batching support natively

**Comment by dhmacs** [comment]
@remorses thanks! I'll probably end up building one.. Should be straightforward to do, I'll tell you how I end up managing this
