### ISSUE TITLE
Generate TypeScript (not transpired to JS)

### ISSUE THREAD

**Issue by jasonkuhrt** [remorses/genql#90]
I have a use-case where I would like to work with the generated genql library as TypeScript instead of built JS with .d.ts files.

Would this be easy to do?

**Comment by remorses** [comment]
Currently there is no way to do that, maybe in next breaking release

**Comment by jasonkuhrt** [comment]
Breaking? This could be opt-in with a new flag. Would you accept a PR to do this?

**Comment by remorses** [comment]
No, i want to simplify the code and only output typescript

**Comment by jasonkuhrt** [comment]
Ah interesting, ok!

**Comment by remorses** [comment]
v3 is out and only outputs Typescript

**Comment by coltenkrauter** [comment]
Is there an option to output to javascript still?

**Comment by remorses** [comment]
No, you can use a transpiler or tsc for that

**Comment by coltenkrauter** [comment]
Thanks for the speedy response!
