### ISSUE TITLE
subscription does not expose "unsubscribe" method nor returns a promise

### ISSUE THREAD

**Issue by o-az** [remorses/genql#93]
[On the website the `subscription` example shows `unsubscribe` being de-structured when using `subscription ](https://genql.vercel.app/docs/usage/subscriptions):

```ts
const { unsubscribe } = await client.subscription({ ... });
```

However when testing this I don't get `unsubscribe` exposed but instead `subscribe`, among other methods (Same happens when using `chain` syntax):

<img width="204" alt="CleanShot 2022-10-13 at 00 20 40@2x" src="https://user-images.githubusercontent.com/23618431/195529046-28dc3b5e-925e-413c-a18d-1c1024c265f6.png">

When looking at `Client` interface in the generated code, it also looks like `subscription` doesn't return a promise:

```ts
export interface Client {
  wsClient?: SubscriptionClient;
  .....
  subscription<R extends subscription_rootRequest>(
    request: R & { __name?: string }
  ): Observable<FieldsSelection<subscription_root, R>>;
  .....
}
```

whereas the example code is `await`ing subscription in both syntaxes.

Versions:
`"@genql/runtime": "^2.10.0"`
`"@genql/cli": "^2.10.0"`

I'm not sure what's going on. I looked at `subscription-transport-request` and the `wsClient` with no luck. That package is also deprecated now.

Is this library abandoned?

**Comment by remorses** [comment]
v3 no longer supports subscriptions

**Comment by shiftlabs1** [comment]
When do we expect the separate package for subscriptions. This is the only bit preventing the upgrade to v3 for us. Thanks

**Comment by remorses** [comment]
You can actually use subscriptions this way
```ts
import { generateSubscriptionOp } from "./generated";
import { createClient as createWsClient } from "ws-client";

const client = createWsClient({
  url: "ws://hey.there:4000/graphql",
});

let { query, variables } = generateSubscriptionOp({
  onCommentAdded: {
    __args: { filter: "ciao" },
    text: true,
    date: true,
    anotherField: jtrue,
  },
});

client.subscribe(
  { query, variables },
  {
    next: (data) => console.log(data),
    error: console.error,
    complete: () => console.log('finished'),
  }
);
```

But now genql does not bundle the websocket client, you need to use a third part package

Docs: https://genql.dev/docs/usage/subscriptions

**Comment by shiftlabs1** [comment]
> You can actually use subscriptions this way
> 
> ```ts
> import { generateSubscriptionOp } from "./generated";
> import { createClient as createWsClient } from "graphql-ws";
> 
> const client = createWsClient({
>   url: "ws://hey.there:4000/graphql",
> });
> 
> let { query, variables } = generateSubscriptionOp({
>   onCommentAdded: {
>     __args: { filter: "ciao" },
>     text: true,
>     date: true,
>     anotherField: jtrue,
>   },
> });
> 
> client.subscribe(
>   { query, variables },
>   {
>     next: (data) => console.log(data),
>     error: console.error,
>     complete: () => console.log('finished'),
>   }
> );
> ```
> 
> But now genql does not bundle the websocket client, you need to use a third part package
> 
> Docs: https://genql.dev/docs/usage/subscriptions

Ah Great. Thanks @remorses , now i can upgrade
