### ISSUE TITLE
Getting error Only absolute URLs are supported

### ISSUE THREAD

**Issue by sunnybogawat** [remorses/genql#94]
Hi, I am using genql to write graphqlmesh queries and I am getting the below error when I m executing one of the queries from my application 
`ClientError: Only absolute URLs are supported
[service] {
[service]   "message": "Only absolute URLs are supported",
[service]   "path": [
[service]     "getRecord"
[service]   ]
[service] }
[service]     at /Users/admin/CIT_Projects/records-api/cit-plce-dome/node_modules/@genql/runtime/dist/fetcher.js:60:35
[service]     at step (/Users/admin/CIT_Projects/records-api/cit-plce-dome/node_modules/tslib/tslib.js:144:27)
`

**Comment by remorses** [comment]
this must be an error coming from your API, not genql
